/-
GzK.lean: tools/gen_gyk.py が生成。錨の列つきの子の述語で証明するシート行。
-/
import GzJ

namespace TRIO
namespace GzK

open Wset Small GwS Gw GwU GwZ GxD GxG GxJ GxK GxL GxN GxP GxR GxT GxV GxW GxY
open GyA GyB GyC GyD GyE GyF GyG GyH GyI GyJ GyK GzD GzF GzH GzI GzJ

/-- ★ シート行 1386。 -/
theorem R1386_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 0, 0)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_topFar (v := 0) ([([some ([(0, 0, 0)] : TrioSeq)] : List (Option TrioSeq))] : List (List (Option TrioSeq))) (RawUs_cons (RawU_cons_some (show ([(0, 0, 0)] : TrioSeq) ∈ Wg (2 * 0) by have h := Wg_up (w := 2 * 0) (Wg_of_starOK (starOK_wordsG (v := 0) (WordsG_nil 0))) (by omega); simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h) rfl (RawU_nil 0)) (RawUs_nil 0)) (by simp [NoTie]) (WordsG_nil 0)))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h

/-- ★ シート行 1387。 -/
theorem R1387_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 0, 0), (1, 1, 1)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_topFar (v := 0) ([([some ([(0, 0, 0)] : TrioSeq)] : List (Option TrioSeq))] : List (List (Option TrioSeq))) (RawUs_cons (RawU_cons_some (show ([(0, 0, 0)] : TrioSeq) ∈ Wg (2 * 0) by have h := Wg_up (w := 2 * 0) (Wg_of_starOK (starOK_wordsG (v := 0) (WordsG_nil 0))) (by omega); simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h) rfl (RawU_nil 0)) (RawUs_nil 0)) (by simp [NoTie]) (WordsG_consT (v := 0) (TF_nil 0) (WordsG_nil 0))))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h

/-- ★ シート行 1388。 -/
theorem R1388_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 0, 0), (1, 1, 1), (2, 1, 1)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_topFar (v := 0) ([([some ([(0, 0, 0)] : TrioSeq)] : List (Option TrioSeq)), ([] : List (Option TrioSeq))] : List (List (Option TrioSeq))) (RawUs_cons (RawU_cons_some (show ([(0, 0, 0)] : TrioSeq) ∈ Wg (2 * 0) by have h := Wg_up (w := 2 * 0) (Wg_of_starOK (starOK_wordsG (v := 0) (WordsG_nil 0))) (by omega); simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h) rfl (RawU_nil 0)) (RawUs_cons (RawU_nil 0) (RawUs_nil 0))) (by simp [NoTie]) (WordsG_nil 0)))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h

/-- ★ シート行 1389。 -/
theorem R1389_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 0, 0), (1, 1, 1), (2, 1, 1), (2, 0, 0)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_topFar (v := 0) ([([some ([(0, 0, 0)] : TrioSeq)] : List (Option TrioSeq)), ([some ([(0, 0, 0)] : TrioSeq)] : List (Option TrioSeq))] : List (List (Option TrioSeq))) (RawUs_cons (RawU_cons_some (show ([(0, 0, 0)] : TrioSeq) ∈ Wg (2 * 0) by have h := Wg_up (w := 2 * 0) (Wg_of_starOK (starOK_wordsG (v := 0) (WordsG_nil 0))) (by omega); simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h) rfl (RawU_nil 0)) (RawUs_cons (RawU_cons_some (show ([(0, 0, 0)] : TrioSeq) ∈ Wg (2 * 0) by have h := Wg_up (w := 2 * 0) (Wg_of_starOK (starOK_wordsG (v := 0) (WordsG_nil 0))) (by omega); simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h) rfl (RawU_nil 0)) (RawUs_nil 0))) (by simp [NoTie]) (WordsG_nil 0)))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h

/-- ★ シート行 1390。 -/
theorem R1390_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 0, 0), (2, 0, 0)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_topFar (v := 0) ([([some ([(0, 0, 0)] : TrioSeq), some ([(0, 0, 0)] : TrioSeq)] : List (Option TrioSeq))] : List (List (Option TrioSeq))) (RawUs_cons (RawU_cons_some (show ([(0, 0, 0)] : TrioSeq) ∈ Wg (2 * 0) by have h := Wg_up (w := 2 * 0) (Wg_of_starOK (starOK_wordsG (v := 0) (WordsG_nil 0))) (by omega); simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h) rfl (RawU_cons_some (show ([(0, 0, 0)] : TrioSeq) ∈ Wg (2 * 0) by have h := Wg_up (w := 2 * 0) (Wg_of_starOK (starOK_wordsG (v := 0) (WordsG_nil 0))) (by omega); simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h) rfl (RawU_nil 0))) (RawUs_nil 0)) (by simp [NoTie]) (WordsG_nil 0)))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h

/-- ★ シート行 1391。 -/
theorem R1391_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 0, 0), (3, 1, 0)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_topFar (v := 0) ([([some ([(0, 0, 0), (1, 1, 0)] : TrioSeq)] : List (Option TrioSeq))] : List (List (Option TrioSeq))) (RawUs_cons (RawU_cons_some (show ([(0, 0, 0), (1, 1, 0)] : TrioSeq) ∈ Wg (2 * 0) by have h := Wg_up (w := 2 * 0) (Wg_of_starOK (starOK_hang (starOK_wordsG (v := 0) (WordsG_nil 0)) (Wg_of_starOK (starOK_wordsG (v := 1) (WordsG_nil 1))) rfl)) (by omega); simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h) rfl (RawU_nil 0)) (RawUs_nil 0)) (by simp [NoTie]) (WordsG_nil 0)))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h

/-- ★ シート行 1392。 -/
theorem R1392_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 0, 0), (3, 1, 1)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_topFar (v := 0) ([([some ([(0, 0, 0), (1, 1, 1)] : TrioSeq)] : List (Option TrioSeq))] : List (List (Option TrioSeq))) (RawUs_cons (RawU_cons_some (show ([(0, 0, 0), (1, 1, 1)] : TrioSeq) ∈ Wg (2 * 0) by have h := Wg_up (w := 2 * 0) (Wg_of_starOK (starOK_wordsG (v := 0) (WordsG_consT (v := 0) (TF_nil 0) (WordsG_nil 0)))) (by omega); simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h) rfl (RawU_nil 0)) (RawUs_nil 0)) (by simp [NoTie]) (WordsG_nil 0)))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h

/-- ★ シート行 1393。 -/
theorem R1393_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 0, 0), (3, 1, 1), (4, 1, 1)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_topFar (v := 0) ([([some ([(0, 0, 0), (1, 1, 1), (2, 1, 1)] : TrioSeq)] : List (Option TrioSeq))] : List (List (Option TrioSeq))) (RawUs_cons (RawU_cons_some (show ([(0, 0, 0), (1, 1, 1), (2, 1, 1)] : TrioSeq) ∈ Wg (2 * 0) by have h := Wg_up (w := 2 * 0) (Wg_of_starOK (starOK_topFar (v := 0) ([([] : List (Option TrioSeq))] : List (List (Option TrioSeq))) (RawUs_cons (RawU_nil 0) (RawUs_nil 0)) (by simp [NoTie]) (WordsG_nil 0))) (by omega); simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h) rfl (RawU_nil 0)) (RawUs_nil 0)) (by simp [NoTie]) (WordsG_nil 0)))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h

/-- ★ シート行 1394。 -/
theorem R1394_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 1, 0)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_topFarTie (v := 0) ([] : List (List (Option TrioSeq))) (RawUs_nil 0) (by simp [NoTie]) ([] : List (Option TrioSeq)) (RawU_nil 0) (by simp [NoTie]) (WordsG_nil 0)))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h

/-- ★ シート行 1395。 -/
theorem R1395_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 1, 0), (1, 1, 0)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_hang (starOK_topFarTie (v := 0) ([] : List (List (Option TrioSeq))) (RawUs_nil 0) (by simp [NoTie]) ([] : List (Option TrioSeq)) (RawU_nil 0) (by simp [NoTie]) (WordsG_nil 0)) (Wg_of_starOK (starOK_wordsG (v := 1) (WordsG_nil 1))) rfl))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h

/-- ★ シート行 1396。 -/
theorem R1396_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 1, 0), (1, 1, 0), (2, 2, 1), (3, 2, 1)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_hang (starOK_topFarTie (v := 0) ([] : List (List (Option TrioSeq))) (RawUs_nil 0) (by simp [NoTie]) ([] : List (Option TrioSeq)) (RawU_nil 0) (by simp [NoTie]) (WordsG_nil 0)) (Wg_of_starOK (starOK_topFar (v := 1) ([([] : List (Option TrioSeq))] : List (List (Option TrioSeq))) (RawUs_cons (RawU_nil 1) (RawUs_nil 1)) (by simp [NoTie]) (WordsG_nil 1))) rfl))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h

/-- ★ シート行 1397。 -/
theorem R1397_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 1, 0), (1, 1, 0), (2, 2, 1), (3, 2, 1), (3, 1, 0)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_hang (starOK_topFarTie (v := 0) ([] : List (List (Option TrioSeq))) (RawUs_nil 0) (by simp [NoTie]) ([] : List (Option TrioSeq)) (RawU_nil 0) (by simp [NoTie]) (WordsG_nil 0)) (Wg_of_starOK (starOK_topFar (v := 1) ([([some ([(0, 1, 0)] : TrioSeq)] : List (Option TrioSeq))] : List (List (Option TrioSeq))) (RawUs_cons (RawU_cons_some (show ([(0, 1, 0)] : TrioSeq) ∈ Wg (2 * 1) by have h := Wg_up (w := 2 * 1) (Wg_of_starOK (starOK_wordsG (v := 1) (WordsG_nil 1))) (by omega); simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h) rfl (RawU_nil 1)) (RawUs_nil 1)) (by simp [NoTie]) (WordsG_nil 1))) rfl))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h

/-- ★ シート行 1398。 -/
theorem R1398_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 1, 0), (1, 1, 0), (2, 2, 1), (3, 2, 1), (3, 1, 0), (2, 2, 0)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_hang (starOK_topFarTie (v := 0) ([] : List (List (Option TrioSeq))) (RawUs_nil 0) (by simp [NoTie]) ([] : List (Option TrioSeq)) (RawU_nil 0) (by simp [NoTie]) (WordsG_nil 0)) (Wg_of_starOK (starOK_hang (starOK_topFar (v := 1) ([([some ([(0, 1, 0)] : TrioSeq)] : List (Option TrioSeq))] : List (List (Option TrioSeq))) (RawUs_cons (RawU_cons_some (show ([(0, 1, 0)] : TrioSeq) ∈ Wg (2 * 1) by have h := Wg_up (w := 2 * 1) (Wg_of_starOK (starOK_wordsG (v := 1) (WordsG_nil 1))) (by omega); simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h) rfl (RawU_nil 1)) (RawUs_nil 1)) (by simp [NoTie]) (WordsG_nil 1)) (Wg_of_starOK (starOK_wordsG (v := 2) (WordsG_nil 2))) rfl)) rfl))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h

/-- ★ シート行 1399。 -/
theorem R1399_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 1, 0), (1, 1, 0), (2, 2, 1), (3, 2, 1), (3, 1, 0), (2, 2, 1)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_hang (starOK_topFarTie (v := 0) ([] : List (List (Option TrioSeq))) (RawUs_nil 0) (by simp [NoTie]) ([] : List (Option TrioSeq)) (RawU_nil 0) (by simp [NoTie]) (WordsG_nil 0)) (Wg_of_starOK (starOK_topFar (v := 1) ([([some ([(0, 1, 0)] : TrioSeq)] : List (Option TrioSeq))] : List (List (Option TrioSeq))) (RawUs_cons (RawU_cons_some (show ([(0, 1, 0)] : TrioSeq) ∈ Wg (2 * 1) by have h := Wg_up (w := 2 * 1) (Wg_of_starOK (starOK_wordsG (v := 1) (WordsG_nil 1))) (by omega); simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h) rfl (RawU_nil 1)) (RawUs_nil 1)) (by simp [NoTie]) (WordsG_consT (v := 1) (TF_nil 1) (WordsG_nil 1)))) rfl))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h

/-- ★ シート行 1400。 -/
theorem R1400_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 1, 0), (1, 1, 0), (2, 2, 1), (3, 2, 1), (3, 1, 0), (2, 2, 1), (3, 2, 0)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_hang (starOK_topFarTie (v := 0) ([] : List (List (Option TrioSeq))) (RawUs_nil 0) (by simp [NoTie]) ([] : List (Option TrioSeq)) (RawU_nil 0) (by simp [NoTie]) (WordsG_nil 0)) (Wg_of_starOK (starOK_topFar (v := 1) ([([some ([(0, 1, 0)] : TrioSeq)] : List (Option TrioSeq))] : List (List (Option TrioSeq))) (RawUs_cons (RawU_cons_some (show ([(0, 1, 0)] : TrioSeq) ∈ Wg (2 * 1) by have h := Wg_up (w := 2 * 1) (Wg_of_starOK (starOK_wordsG (v := 1) (WordsG_nil 1))) (by omega); simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h) rfl (RawU_nil 1)) (RawUs_nil 1)) (by simp [NoTie]) (WordsG_consT (v := 1) (TF_tieG (u := 1) (TF_nil 1) (GF_of_GPF (GPF_nil1 1))) (WordsG_nil 1)))) rfl))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h

/-- ★ シート行 1401。 -/
theorem R1401_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 1, 0), (1, 1, 0), (2, 2, 1), (3, 2, 1), (3, 1, 0), (2, 2, 1), (3, 2, 0), (4, 3, 0)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_hang (starOK_topFarTie (v := 0) ([] : List (List (Option TrioSeq))) (RawUs_nil 0) (by simp [NoTie]) ([] : List (Option TrioSeq)) (RawU_nil 0) (by simp [NoTie]) (WordsG_nil 0)) (Wg_of_starOK (starOK_topFar (v := 1) ([([some ([(0, 1, 0)] : TrioSeq)] : List (Option TrioSeq))] : List (List (Option TrioSeq))) (RawUs_cons (RawU_cons_some (show ([(0, 1, 0)] : TrioSeq) ∈ Wg (2 * 1) by have h := Wg_up (w := 2 * 1) (Wg_of_starOK (starOK_wordsG (v := 1) (WordsG_nil 1))) (by omega); simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h) rfl (RawU_nil 1)) (RawUs_nil 1)) (by simp [NoTie]) (WordsG_consT (v := 1) (TF_tieG (u := 1) (TF_nil 1) (GF_of_GPF (GPF_node (A := []) (o := 1) (by decide) (by decide) (by decide) (b := 1) (τ := 2) [] (by decide) (GPF_nil1 1) (GPF_nil (A := []) (o := 2) (by decide) (by decide) 1)))) (WordsG_nil 1)))) rfl))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h

/-- ★ シート行 1402。 -/
theorem R1402_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 1, 0), (1, 1, 0), (2, 2, 1), (3, 2, 1), (3, 1, 0), (2, 2, 1), (3, 2, 0), (4, 3, 1)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_hang (starOK_topFarTie (v := 0) ([] : List (List (Option TrioSeq))) (RawUs_nil 0) (by simp [NoTie]) ([] : List (Option TrioSeq)) (RawU_nil 0) (by simp [NoTie]) (WordsG_nil 0)) (Wg_of_starOK (starOK_topFar (v := 1) ([([some ([(0, 1, 0)] : TrioSeq)] : List (Option TrioSeq))] : List (List (Option TrioSeq))) (RawUs_cons (RawU_cons_some (show ([(0, 1, 0)] : TrioSeq) ∈ Wg (2 * 1) by have h := Wg_up (w := 2 * 1) (Wg_of_starOK (starOK_wordsG (v := 1) (WordsG_nil 1))) (by omega); simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h) rfl (RawU_nil 1)) (RawUs_nil 1)) (by simp [NoTie]) (WordsG_consT (v := 1) (TF_tieG (u := 1) (TF_nil 1) (GF_of_GPF (GPF_of_PVF (PVF_snoc (A := []) (o := 1) (by decide) (PVF_nil1 1) (RLF_nil (A := []) (o := 1) (by decide) (by decide) (by decide) 1))))) (WordsG_nil 1)))) rfl))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h

/-- ★ シート行 1403。 -/
theorem R1403_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 1, 0), (1, 1, 0), (2, 2, 1), (3, 2, 1), (3, 1, 0), (2, 2, 1), (3, 2, 0), (4, 3, 1), (5, 3, 1)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_hang (starOK_topFarTie (v := 0) ([] : List (List (Option TrioSeq))) (RawUs_nil 0) (by simp [NoTie]) ([] : List (Option TrioSeq)) (RawU_nil 0) (by simp [NoTie]) (WordsG_nil 0)) (Wg_of_starOK (starOK_topFar (v := 1) ([([some ([(0, 1, 0)] : TrioSeq)] : List (Option TrioSeq))] : List (List (Option TrioSeq))) (RawUs_cons (RawU_cons_some (show ([(0, 1, 0)] : TrioSeq) ∈ Wg (2 * 1) by have h := Wg_up (w := 2 * 1) (Wg_of_starOK (starOK_wordsG (v := 1) (WordsG_nil 1))) (by omega); simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h) rfl (RawU_nil 1)) (RawUs_nil 1)) (by simp [NoTie]) (WordsG_consT (v := 1) (TF_tieG (u := 1) (TF_nil 1) (GF_of_GPF (GPF_of_PVF (PVF_farU (A := []) (o := 1) (by decide) (by decide) (by decide) 1 ([([] : List (Option TrioSeq))] : List (List (Option TrioSeq))) (RawUs_cons (RawU_nil 1) (RawUs_nil 1)))))) (WordsG_nil 1)))) rfl))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h

/-- ★ シート行 1404。 -/
theorem R1404_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 1, 0), (1, 1, 0), (2, 2, 1), (3, 2, 1), (3, 1, 0), (2, 2, 1), (3, 2, 0), (4, 3, 1), (5, 3, 1), (5, 1, 0)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_hang (starOK_topFarTie (v := 0) ([] : List (List (Option TrioSeq))) (RawUs_nil 0) (by simp [NoTie]) ([] : List (Option TrioSeq)) (RawU_nil 0) (by simp [NoTie]) (WordsG_nil 0)) (Wg_of_starOK (starOK_topFar (v := 1) ([([some ([(0, 1, 0)] : TrioSeq)] : List (Option TrioSeq))] : List (List (Option TrioSeq))) (RawUs_cons (RawU_cons_some (show ([(0, 1, 0)] : TrioSeq) ∈ Wg (2 * 1) by have h := Wg_up (w := 2 * 1) (Wg_of_starOK (starOK_wordsG (v := 1) (WordsG_nil 1))) (by omega); simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h) rfl (RawU_nil 1)) (RawUs_nil 1)) (by simp [NoTie]) (WordsG_consT (v := 1) (TF_tieG (u := 1) (TF_nil 1) (GF_of_GPF (GPF_of_PVF (PVF_farU (A := []) (o := 1) (by decide) (by decide) (by decide) 1 ([([some ([(0, 1, 0)] : TrioSeq)] : List (Option TrioSeq))] : List (List (Option TrioSeq))) (RawUs_cons (RawU_cons_some (show ([(0, 1, 0)] : TrioSeq) ∈ Wg (2 * 1) by have h := Wg_up (w := 2 * 1) (Wg_of_starOK (starOK_wordsG (v := 1) (WordsG_nil 1))) (by omega); simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h) rfl (RawU_nil 1)) (RawUs_nil 1)))))) (WordsG_nil 1)))) rfl))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h

/-- ★ シート行 1405。 -/
theorem R1405_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 1, 0), (1, 1, 0), (2, 2, 1), (3, 2, 1), (3, 1, 0), (2, 2, 1), (3, 2, 0), (4, 3, 1), (5, 3, 1), (5, 1, 0), (4, 3, 0)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_hang (starOK_topFarTie (v := 0) ([] : List (List (Option TrioSeq))) (RawUs_nil 0) (by simp [NoTie]) ([] : List (Option TrioSeq)) (RawU_nil 0) (by simp [NoTie]) (WordsG_nil 0)) (Wg_of_starOK (starOK_topFar (v := 1) ([([some ([(0, 1, 0)] : TrioSeq)] : List (Option TrioSeq))] : List (List (Option TrioSeq))) (RawUs_cons (RawU_cons_some (show ([(0, 1, 0)] : TrioSeq) ∈ Wg (2 * 1) by have h := Wg_up (w := 2 * 1) (Wg_of_starOK (starOK_wordsG (v := 1) (WordsG_nil 1))) (by omega); simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h) rfl (RawU_nil 1)) (RawUs_nil 1)) (by simp [NoTie]) (WordsG_consT (v := 1) (TF_tieG (u := 1) (TF_nil 1) (GF_of_GPF (GPF_node (A := []) (o := 1) (by decide) (by decide) (by decide) (b := 1) (τ := 2) [] (by decide) (GPF_of_PVF (PVF_farU (A := []) (o := 1) (by decide) (by decide) (by decide) 1 ([([some ([(0, 1, 0)] : TrioSeq)] : List (Option TrioSeq))] : List (List (Option TrioSeq))) (RawUs_cons (RawU_cons_some (show ([(0, 1, 0)] : TrioSeq) ∈ Wg (2 * 1) by have h := Wg_up (w := 2 * 1) (Wg_of_starOK (starOK_wordsG (v := 1) (WordsG_nil 1))) (by omega); simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h) rfl (RawU_nil 1)) (RawUs_nil 1)))) (GPF_nil (A := []) (o := 2) (by decide) (by decide) 1)))) (WordsG_nil 1)))) rfl))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h

/-- ★ シート行 1406。 -/
theorem R1406_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 1, 0), (1, 1, 0), (2, 2, 1), (3, 2, 1), (3, 1, 0), (2, 2, 1), (3, 2, 0), (4, 3, 1), (5, 3, 1), (5, 1, 0), (4, 3, 0), (5, 4, 1), (6, 4, 1), (6, 1, 0), (5, 4, 0)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_hang (starOK_topFarTie (v := 0) ([] : List (List (Option TrioSeq))) (RawUs_nil 0) (by simp [NoTie]) ([] : List (Option TrioSeq)) (RawU_nil 0) (by simp [NoTie]) (WordsG_nil 0)) (Wg_of_starOK (starOK_topFar (v := 1) ([([some ([(0, 1, 0)] : TrioSeq)] : List (Option TrioSeq))] : List (List (Option TrioSeq))) (RawUs_cons (RawU_cons_some (show ([(0, 1, 0)] : TrioSeq) ∈ Wg (2 * 1) by have h := Wg_up (w := 2 * 1) (Wg_of_starOK (starOK_wordsG (v := 1) (WordsG_nil 1))) (by omega); simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h) rfl (RawU_nil 1)) (RawUs_nil 1)) (by simp [NoTie]) (WordsG_consT (v := 1) (TF_tieG (u := 1) (TF_nil 1) (GF_of_GPF (GPF_node (A := []) (o := 1) (by decide) (by decide) (by decide) (b := 1) (τ := 2) [] (by decide) (GPF_of_PVF (PVF_farU (A := []) (o := 1) (by decide) (by decide) (by decide) 1 ([([some ([(0, 1, 0)] : TrioSeq)] : List (Option TrioSeq))] : List (List (Option TrioSeq))) (RawUs_cons (RawU_cons_some (show ([(0, 1, 0)] : TrioSeq) ∈ Wg (2 * 1) by have h := Wg_up (w := 2 * 1) (Wg_of_starOK (starOK_wordsG (v := 1) (WordsG_nil 1))) (by omega); simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h) rfl (RawU_nil 1)) (RawUs_nil 1)))) (GPF_node (A := []) (o := 2) (by decide) (by decide) (by decide) (b := 1) (τ := 3) [] (by decide) (GPF_of_PVF (PVF_farU (A := []) (o := 2) (by decide) (by decide) (by decide) 1 ([([some ([(0, 1, 0)] : TrioSeq)] : List (Option TrioSeq))] : List (List (Option TrioSeq))) (RawUs_cons (RawU_cons_some (show ([(0, 1, 0)] : TrioSeq) ∈ Wg (2 * 1) by have h := Wg_up (w := 2 * 1) (Wg_of_starOK (starOK_wordsG (v := 1) (WordsG_nil 1))) (by omega); simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h) rfl (RawU_nil 1)) (RawUs_nil 1)))) (GPF_nil (A := []) (o := 3) (by decide) (by decide) 1))))) (WordsG_nil 1)))) rfl))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h

/-- ★ シート行 1407。 -/
theorem R1407_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 1, 0), (1, 1, 0), (2, 2, 1), (3, 2, 1), (3, 1, 0), (2, 2, 1), (3, 2, 0), (4, 3, 1), (5, 3, 1), (5, 1, 0), (4, 3, 1)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_hang (starOK_topFarTie (v := 0) ([] : List (List (Option TrioSeq))) (RawUs_nil 0) (by simp [NoTie]) ([] : List (Option TrioSeq)) (RawU_nil 0) (by simp [NoTie]) (WordsG_nil 0)) (Wg_of_starOK (starOK_topFar (v := 1) ([([some ([(0, 1, 0)] : TrioSeq)] : List (Option TrioSeq))] : List (List (Option TrioSeq))) (RawUs_cons (RawU_cons_some (show ([(0, 1, 0)] : TrioSeq) ∈ Wg (2 * 1) by have h := Wg_up (w := 2 * 1) (Wg_of_starOK (starOK_wordsG (v := 1) (WordsG_nil 1))) (by omega); simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h) rfl (RawU_nil 1)) (RawUs_nil 1)) (by simp [NoTie]) (WordsG_consT (v := 1) (TF_tieG (u := 1) (TF_nil 1) (GF_of_GPF (GPF_of_PVF (PVF_snoc (A := []) (o := 1) (by decide) (PVF_farU (A := []) (o := 1) (by decide) (by decide) (by decide) 1 ([([some ([(0, 1, 0)] : TrioSeq)] : List (Option TrioSeq))] : List (List (Option TrioSeq))) (RawUs_cons (RawU_cons_some (show ([(0, 1, 0)] : TrioSeq) ∈ Wg (2 * 1) by have h := Wg_up (w := 2 * 1) (Wg_of_starOK (starOK_wordsG (v := 1) (WordsG_nil 1))) (by omega); simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h) rfl (RawU_nil 1)) (RawUs_nil 1))) (RLF_nil (A := []) (o := 1) (by decide) (by decide) (by decide) 1))))) (WordsG_nil 1)))) rfl))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h

/-- ★ シート行 1408。 -/
theorem R1408_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 1, 0), (1, 1, 0), (2, 2, 1), (3, 2, 1), (3, 1, 0), (2, 2, 1), (3, 2, 0), (4, 3, 1), (5, 3, 1), (5, 1, 0), (4, 3, 1), (5, 3, 0), (6, 4, 1), (7, 4, 1), (7, 1, 0)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_hang (starOK_topFarTie (v := 0) ([] : List (List (Option TrioSeq))) (RawUs_nil 0) (by simp [NoTie]) ([] : List (Option TrioSeq)) (RawU_nil 0) (by simp [NoTie]) (WordsG_nil 0)) (Wg_of_starOK (starOK_topFar (v := 1) ([([some ([(0, 1, 0)] : TrioSeq)] : List (Option TrioSeq))] : List (List (Option TrioSeq))) (RawUs_cons (RawU_cons_some (show ([(0, 1, 0)] : TrioSeq) ∈ Wg (2 * 1) by have h := Wg_up (w := 2 * 1) (Wg_of_starOK (starOK_wordsG (v := 1) (WordsG_nil 1))) (by omega); simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h) rfl (RawU_nil 1)) (RawUs_nil 1)) (by simp [NoTie]) (WordsG_consT (v := 1) (TF_tieG (u := 1) (TF_nil 1) (GF_of_GPF (GPF_of_PVF (PVF_snoc (A := []) (o := 1) (by decide) (PVF_farU (A := []) (o := 1) (by decide) (by decide) (by decide) 1 ([([some ([(0, 1, 0)] : TrioSeq)] : List (Option TrioSeq))] : List (List (Option TrioSeq))) (RawUs_cons (RawU_cons_some (show ([(0, 1, 0)] : TrioSeq) ∈ Wg (2 * 1) by have h := Wg_up (w := 2 * 1) (Wg_of_starOK (starOK_wordsG (v := 1) (WordsG_nil 1))) (by omega); simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h) rfl (RawU_nil 1)) (RawUs_nil 1))) (RLF_child (A := []) (o := 1) (by decide) (by decide) (by decide) (b := 1) (τ := 2) [1] (by decide) (by decide) (RLF_nil (A := []) (o := 1) (by decide) (by decide) (by decide) 1) (GPF_of_PVF (PVF_farU (A := [1]) (o := 2) (by decide) (by decide) (by decide) 1 ([([some ([(0, 1, 0)] : TrioSeq)] : List (Option TrioSeq))] : List (List (Option TrioSeq))) (RawUs_cons (RawU_cons_some (show ([(0, 1, 0)] : TrioSeq) ∈ Wg (2 * 1) by have h := Wg_up (w := 2 * 1) (Wg_of_starOK (starOK_wordsG (v := 1) (WordsG_nil 1))) (by omega); simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h) rfl (RawU_nil 1)) (RawUs_nil 1))))))))) (WordsG_nil 1)))) rfl))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h

/-- ★ シート行 1409。 -/
theorem R1409_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 1, 0), (1, 1, 0), (2, 2, 1), (3, 2, 1), (3, 1, 0), (2, 2, 1), (3, 2, 0), (4, 3, 1), (5, 3, 1), (5, 1, 0), (4, 3, 1), (5, 3, 0), (6, 4, 1), (7, 4, 1), (7, 1, 0), (6, 4, 0)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_hang (starOK_topFarTie (v := 0) ([] : List (List (Option TrioSeq))) (RawUs_nil 0) (by simp [NoTie]) ([] : List (Option TrioSeq)) (RawU_nil 0) (by simp [NoTie]) (WordsG_nil 0)) (Wg_of_starOK (starOK_topFar (v := 1) ([([some ([(0, 1, 0)] : TrioSeq)] : List (Option TrioSeq))] : List (List (Option TrioSeq))) (RawUs_cons (RawU_cons_some (show ([(0, 1, 0)] : TrioSeq) ∈ Wg (2 * 1) by have h := Wg_up (w := 2 * 1) (Wg_of_starOK (starOK_wordsG (v := 1) (WordsG_nil 1))) (by omega); simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h) rfl (RawU_nil 1)) (RawUs_nil 1)) (by simp [NoTie]) (WordsG_consT (v := 1) (TF_tieG (u := 1) (TF_nil 1) (GF_of_GPF (GPF_of_PVF (PVF_snoc (A := []) (o := 1) (by decide) (PVF_farU (A := []) (o := 1) (by decide) (by decide) (by decide) 1 ([([some ([(0, 1, 0)] : TrioSeq)] : List (Option TrioSeq))] : List (List (Option TrioSeq))) (RawUs_cons (RawU_cons_some (show ([(0, 1, 0)] : TrioSeq) ∈ Wg (2 * 1) by have h := Wg_up (w := 2 * 1) (Wg_of_starOK (starOK_wordsG (v := 1) (WordsG_nil 1))) (by omega); simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h) rfl (RawU_nil 1)) (RawUs_nil 1))) (RLF_child (A := []) (o := 1) (by decide) (by decide) (by decide) (b := 1) (τ := 2) [1] (by decide) (by decide) (RLF_nil (A := []) (o := 1) (by decide) (by decide) (by decide) 1) (GPF_node (A := [1]) (o := 2) (by decide) (by decide) (by decide) (b := 1) (τ := 3) [1] (by decide) (GPF_of_PVF (PVF_farU (A := [1]) (o := 2) (by decide) (by decide) (by decide) 1 ([([some ([(0, 1, 0)] : TrioSeq)] : List (Option TrioSeq))] : List (List (Option TrioSeq))) (RawUs_cons (RawU_cons_some (show ([(0, 1, 0)] : TrioSeq) ∈ Wg (2 * 1) by have h := Wg_up (w := 2 * 1) (Wg_of_starOK (starOK_wordsG (v := 1) (WordsG_nil 1))) (by omega); simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h) rfl (RawU_nil 1)) (RawUs_nil 1)))) (GPF_nil (A := [1]) (o := 3) (by decide) (by decide) 1))))))) (WordsG_nil 1)))) rfl))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h

/-- ★ シート行 1410。 -/
theorem R1410_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 1, 0), (1, 1, 0), (2, 2, 1), (3, 2, 1), (3, 1, 0), (2, 2, 1), (3, 2, 0), (4, 3, 1), (5, 3, 1), (5, 1, 0), (4, 3, 1), (5, 3, 0), (6, 4, 1), (7, 4, 1), (7, 1, 0), (6, 4, 1)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_hang (starOK_topFarTie (v := 0) ([] : List (List (Option TrioSeq))) (RawUs_nil 0) (by simp [NoTie]) ([] : List (Option TrioSeq)) (RawU_nil 0) (by simp [NoTie]) (WordsG_nil 0)) (Wg_of_starOK (starOK_topFar (v := 1) ([([some ([(0, 1, 0)] : TrioSeq)] : List (Option TrioSeq))] : List (List (Option TrioSeq))) (RawUs_cons (RawU_cons_some (show ([(0, 1, 0)] : TrioSeq) ∈ Wg (2 * 1) by have h := Wg_up (w := 2 * 1) (Wg_of_starOK (starOK_wordsG (v := 1) (WordsG_nil 1))) (by omega); simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h) rfl (RawU_nil 1)) (RawUs_nil 1)) (by simp [NoTie]) (WordsG_consT (v := 1) (TF_tieG (u := 1) (TF_nil 1) (GF_of_GPF (GPF_of_PVF (PVF_snoc (A := []) (o := 1) (by decide) (PVF_farU (A := []) (o := 1) (by decide) (by decide) (by decide) 1 ([([some ([(0, 1, 0)] : TrioSeq)] : List (Option TrioSeq))] : List (List (Option TrioSeq))) (RawUs_cons (RawU_cons_some (show ([(0, 1, 0)] : TrioSeq) ∈ Wg (2 * 1) by have h := Wg_up (w := 2 * 1) (Wg_of_starOK (starOK_wordsG (v := 1) (WordsG_nil 1))) (by omega); simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h) rfl (RawU_nil 1)) (RawUs_nil 1))) (RLF_child (A := []) (o := 1) (by decide) (by decide) (by decide) (b := 1) (τ := 2) [1] (by decide) (by decide) (RLF_nil (A := []) (o := 1) (by decide) (by decide) (by decide) 1) (GPF_of_PVF (PVF_snoc (A := [1]) (o := 2) (by decide) (PVF_farU (A := [1]) (o := 2) (by decide) (by decide) (by decide) 1 ([([some ([(0, 1, 0)] : TrioSeq)] : List (Option TrioSeq))] : List (List (Option TrioSeq))) (RawUs_cons (RawU_cons_some (show ([(0, 1, 0)] : TrioSeq) ∈ Wg (2 * 1) by have h := Wg_up (w := 2 * 1) (Wg_of_starOK (starOK_wordsG (v := 1) (WordsG_nil 1))) (by omega); simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h) rfl (RawU_nil 1)) (RawUs_nil 1))) (RLF_nil (A := [1]) (o := 2) (by decide) (by decide) (by decide) 1)))))))) (WordsG_nil 1)))) rfl))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h

/-- ★ シート行 1411。 -/
theorem R1411_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 1, 0), (1, 1, 0), (2, 2, 1), (3, 2, 1), (3, 1, 0), (2, 2, 1), (3, 2, 1)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_hang (starOK_topFarTie (v := 0) ([] : List (List (Option TrioSeq))) (RawUs_nil 0) (by simp [NoTie]) ([] : List (Option TrioSeq)) (RawU_nil 0) (by simp [NoTie]) (WordsG_nil 0)) (Wg_of_starOK (starOK_topFar (v := 1) ([([some ([(0, 1, 0)] : TrioSeq)] : List (Option TrioSeq)), ([] : List (Option TrioSeq))] : List (List (Option TrioSeq))) (RawUs_cons (RawU_cons_some (show ([(0, 1, 0)] : TrioSeq) ∈ Wg (2 * 1) by have h := Wg_up (w := 2 * 1) (Wg_of_starOK (starOK_wordsG (v := 1) (WordsG_nil 1))) (by omega); simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h) rfl (RawU_nil 1)) (RawUs_cons (RawU_nil 1) (RawUs_nil 1))) (by simp [NoTie]) (WordsG_nil 1))) rfl))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h

/-- ★ シート行 1412。 -/
theorem R1412_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 1, 0), (1, 1, 0), (2, 2, 1), (3, 2, 1), (3, 1, 0), (2, 2, 1), (3, 2, 1), (2, 2, 1), (3, 2, 1)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_hang (starOK_topFarTie (v := 0) ([] : List (List (Option TrioSeq))) (RawUs_nil 0) (by simp [NoTie]) ([] : List (Option TrioSeq)) (RawU_nil 0) (by simp [NoTie]) (WordsG_nil 0)) (Wg_of_starOK (starOK_topFar (v := 1) ([([some ([(0, 1, 0)] : TrioSeq)] : List (Option TrioSeq)), ([] : List (Option TrioSeq)), ([] : List (Option TrioSeq))] : List (List (Option TrioSeq))) (RawUs_cons (RawU_cons_some (show ([(0, 1, 0)] : TrioSeq) ∈ Wg (2 * 1) by have h := Wg_up (w := 2 * 1) (Wg_of_starOK (starOK_wordsG (v := 1) (WordsG_nil 1))) (by omega); simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h) rfl (RawU_nil 1)) (RawUs_cons (RawU_nil 1) (RawUs_cons (RawU_nil 1) (RawUs_nil 1)))) (by simp [NoTie]) (WordsG_nil 1))) rfl))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h

/-- ★ シート行 1413。 -/
theorem R1413_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 1, 0), (1, 1, 0), (2, 2, 1), (3, 2, 1), (3, 1, 0), (2, 2, 1), (3, 2, 1), (3, 0, 0)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_hang (starOK_topFarTie (v := 0) ([] : List (List (Option TrioSeq))) (RawUs_nil 0) (by simp [NoTie]) ([] : List (Option TrioSeq)) (RawU_nil 0) (by simp [NoTie]) (WordsG_nil 0)) (Wg_of_starOK (starOK_topFar (v := 1) ([([some ([(0, 1, 0)] : TrioSeq)] : List (Option TrioSeq)), ([some ([(0, 0, 0)] : TrioSeq)] : List (Option TrioSeq))] : List (List (Option TrioSeq))) (RawUs_cons (RawU_cons_some (show ([(0, 1, 0)] : TrioSeq) ∈ Wg (2 * 1) by have h := Wg_up (w := 2 * 1) (Wg_of_starOK (starOK_wordsG (v := 1) (WordsG_nil 1))) (by omega); simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h) rfl (RawU_nil 1)) (RawUs_cons (RawU_cons_some (show ([(0, 0, 0)] : TrioSeq) ∈ Wg (2 * 1) by have h := Wg_up (w := 2 * 1) (Wg_of_starOK (starOK_wordsG (v := 0) (WordsG_nil 0))) (by omega); simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h) rfl (RawU_nil 1)) (RawUs_nil 1))) (by simp [NoTie]) (WordsG_nil 1))) rfl))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h

/-- ★ シート行 1414。 -/
theorem R1414_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 1, 0), (1, 1, 0), (2, 2, 1), (3, 2, 1), (3, 1, 0), (2, 2, 1), (3, 2, 1), (3, 1, 0)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_hang (starOK_topFarTie (v := 0) ([] : List (List (Option TrioSeq))) (RawUs_nil 0) (by simp [NoTie]) ([] : List (Option TrioSeq)) (RawU_nil 0) (by simp [NoTie]) (WordsG_nil 0)) (Wg_of_starOK (starOK_topFar (v := 1) ([([some ([(0, 1, 0)] : TrioSeq)] : List (Option TrioSeq)), ([some ([(0, 1, 0)] : TrioSeq)] : List (Option TrioSeq))] : List (List (Option TrioSeq))) (RawUs_cons (RawU_cons_some (show ([(0, 1, 0)] : TrioSeq) ∈ Wg (2 * 1) by have h := Wg_up (w := 2 * 1) (Wg_of_starOK (starOK_wordsG (v := 1) (WordsG_nil 1))) (by omega); simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h) rfl (RawU_nil 1)) (RawUs_cons (RawU_cons_some (show ([(0, 1, 0)] : TrioSeq) ∈ Wg (2 * 1) by have h := Wg_up (w := 2 * 1) (Wg_of_starOK (starOK_wordsG (v := 1) (WordsG_nil 1))) (by omega); simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h) rfl (RawU_nil 1)) (RawUs_nil 1))) (by simp [NoTie]) (WordsG_nil 1))) rfl))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h

/-- ★ シート行 1415。 -/
theorem R1415_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 1, 0), (1, 1, 0), (2, 2, 1), (3, 2, 1), (3, 1, 0), (3, 0, 0)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_hang (starOK_topFarTie (v := 0) ([] : List (List (Option TrioSeq))) (RawUs_nil 0) (by simp [NoTie]) ([] : List (Option TrioSeq)) (RawU_nil 0) (by simp [NoTie]) (WordsG_nil 0)) (Wg_of_starOK (starOK_topFar (v := 1) ([([some ([(0, 1, 0)] : TrioSeq), some ([(0, 0, 0)] : TrioSeq)] : List (Option TrioSeq))] : List (List (Option TrioSeq))) (RawUs_cons (RawU_cons_some (show ([(0, 1, 0)] : TrioSeq) ∈ Wg (2 * 1) by have h := Wg_up (w := 2 * 1) (Wg_of_starOK (starOK_wordsG (v := 1) (WordsG_nil 1))) (by omega); simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h) rfl (RawU_cons_some (show ([(0, 0, 0)] : TrioSeq) ∈ Wg (2 * 1) by have h := Wg_up (w := 2 * 1) (Wg_of_starOK (starOK_wordsG (v := 0) (WordsG_nil 0))) (by omega); simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h) rfl (RawU_nil 1))) (RawUs_nil 1)) (by simp [NoTie]) (WordsG_nil 1))) rfl))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h

/-- ★ シート行 1416。 -/
theorem R1416_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 1, 0), (1, 1, 0), (2, 2, 1), (3, 2, 1), (3, 1, 0), (3, 1, 0)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_hang (starOK_topFarTie (v := 0) ([] : List (List (Option TrioSeq))) (RawUs_nil 0) (by simp [NoTie]) ([] : List (Option TrioSeq)) (RawU_nil 0) (by simp [NoTie]) (WordsG_nil 0)) (Wg_of_starOK (starOK_topFar (v := 1) ([([some ([(0, 1, 0)] : TrioSeq), some ([(0, 1, 0)] : TrioSeq)] : List (Option TrioSeq))] : List (List (Option TrioSeq))) (RawUs_cons (RawU_cons_some (show ([(0, 1, 0)] : TrioSeq) ∈ Wg (2 * 1) by have h := Wg_up (w := 2 * 1) (Wg_of_starOK (starOK_wordsG (v := 1) (WordsG_nil 1))) (by omega); simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h) rfl (RawU_cons_some (show ([(0, 1, 0)] : TrioSeq) ∈ Wg (2 * 1) by have h := Wg_up (w := 2 * 1) (Wg_of_starOK (starOK_wordsG (v := 1) (WordsG_nil 1))) (by omega); simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h) rfl (RawU_nil 1))) (RawUs_nil 1)) (by simp [NoTie]) (WordsG_nil 1))) rfl))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h

/-- ★ シート行 1417。 -/
theorem R1417_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 1, 0), (1, 1, 0), (2, 2, 1), (3, 2, 1), (3, 1, 0), (4, 2, 0)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_hang (starOK_topFarTie (v := 0) ([] : List (List (Option TrioSeq))) (RawUs_nil 0) (by simp [NoTie]) ([] : List (Option TrioSeq)) (RawU_nil 0) (by simp [NoTie]) (WordsG_nil 0)) (Wg_of_starOK (starOK_topFar (v := 1) ([([some ([(0, 1, 0), (1, 2, 0)] : TrioSeq)] : List (Option TrioSeq))] : List (List (Option TrioSeq))) (RawUs_cons (RawU_cons_some (show ([(0, 1, 0), (1, 2, 0)] : TrioSeq) ∈ Wg (2 * 1) by have h := Wg_up (w := 2 * 1) (Wg_of_starOK (starOK_hang (starOK_wordsG (v := 1) (WordsG_nil 1)) (Wg_of_starOK (starOK_wordsG (v := 2) (WordsG_nil 2))) rfl)) (by omega); simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h) rfl (RawU_nil 1)) (RawUs_nil 1)) (by simp [NoTie]) (WordsG_nil 1))) rfl))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h

/-- ★ シート行 1418。 -/
theorem R1418_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 1, 0), (1, 1, 0), (2, 2, 1), (3, 2, 1), (3, 1, 0), (4, 2, 1)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_hang (starOK_topFarTie (v := 0) ([] : List (List (Option TrioSeq))) (RawUs_nil 0) (by simp [NoTie]) ([] : List (Option TrioSeq)) (RawU_nil 0) (by simp [NoTie]) (WordsG_nil 0)) (Wg_of_starOK (starOK_topFar (v := 1) ([([some ([(0, 1, 0), (1, 2, 1)] : TrioSeq)] : List (Option TrioSeq))] : List (List (Option TrioSeq))) (RawUs_cons (RawU_cons_some (show ([(0, 1, 0), (1, 2, 1)] : TrioSeq) ∈ Wg (2 * 1) by have h := Wg_up (w := 2 * 1) (Wg_of_starOK (starOK_wordsG (v := 1) (WordsG_consT (v := 1) (TF_nil 1) (WordsG_nil 1)))) (by omega); simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h) rfl (RawU_nil 1)) (RawUs_nil 1)) (by simp [NoTie]) (WordsG_nil 1))) rfl))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h

/-- ★ シート行 1419。 -/
theorem R1419_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 1, 0), (1, 1, 0), (2, 2, 1), (3, 2, 1), (3, 1, 0), (4, 2, 1), (5, 2, 1)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_hang (starOK_topFarTie (v := 0) ([] : List (List (Option TrioSeq))) (RawUs_nil 0) (by simp [NoTie]) ([] : List (Option TrioSeq)) (RawU_nil 0) (by simp [NoTie]) (WordsG_nil 0)) (Wg_of_starOK (starOK_topFar (v := 1) ([([some ([(0, 1, 0), (1, 2, 1), (2, 2, 1)] : TrioSeq)] : List (Option TrioSeq))] : List (List (Option TrioSeq))) (RawUs_cons (RawU_cons_some (show ([(0, 1, 0), (1, 2, 1), (2, 2, 1)] : TrioSeq) ∈ Wg (2 * 1) by have h := Wg_up (w := 2 * 1) (Wg_of_starOK (starOK_topFar (v := 1) ([([] : List (Option TrioSeq))] : List (List (Option TrioSeq))) (RawUs_cons (RawU_nil 1) (RawUs_nil 1)) (by simp [NoTie]) (WordsG_nil 1))) (by omega); simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h) rfl (RawU_nil 1)) (RawUs_nil 1)) (by simp [NoTie]) (WordsG_nil 1))) rfl))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h

/-- ★ シート行 1420。 -/
theorem R1420_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 1, 0), (1, 1, 0), (2, 2, 1), (3, 2, 1), (3, 1, 0), (4, 2, 1), (5, 2, 1), (5, 1, 0)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_hang (starOK_topFarTie (v := 0) ([] : List (List (Option TrioSeq))) (RawUs_nil 0) (by simp [NoTie]) ([] : List (Option TrioSeq)) (RawU_nil 0) (by simp [NoTie]) (WordsG_nil 0)) (Wg_of_starOK (starOK_topFar (v := 1) ([([some ([(0, 1, 0), (1, 2, 1), (2, 2, 1), (2, 1, 0)] : TrioSeq)] : List (Option TrioSeq))] : List (List (Option TrioSeq))) (RawUs_cons (RawU_cons_some (show ([(0, 1, 0), (1, 2, 1), (2, 2, 1), (2, 1, 0)] : TrioSeq) ∈ Wg (2 * 1) by have h := Wg_up (w := 2 * 1) (Wg_of_starOK (starOK_topFar (v := 1) ([([some ([(0, 1, 0)] : TrioSeq)] : List (Option TrioSeq))] : List (List (Option TrioSeq))) (RawUs_cons (RawU_cons_some (show ([(0, 1, 0)] : TrioSeq) ∈ Wg (2 * 1) by have h := Wg_up (w := 2 * 1) (Wg_of_starOK (starOK_wordsG (v := 1) (WordsG_nil 1))) (by omega); simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h) rfl (RawU_nil 1)) (RawUs_nil 1)) (by simp [NoTie]) (WordsG_nil 1))) (by omega); simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h) rfl (RawU_nil 1)) (RawUs_nil 1)) (by simp [NoTie]) (WordsG_nil 1))) rfl))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h

/-- ★ シート行 1421。 -/
theorem R1421_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 1, 0), (1, 1, 0), (2, 2, 1), (3, 2, 1), (3, 2, 0)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_hang (starOK_topFarTie (v := 0) ([] : List (List (Option TrioSeq))) (RawUs_nil 0) (by simp [NoTie]) ([] : List (Option TrioSeq)) (RawU_nil 0) (by simp [NoTie]) (WordsG_nil 0)) (Wg_of_starOK (starOK_topFarTie (v := 1) ([] : List (List (Option TrioSeq))) (RawUs_nil 1) (by simp [NoTie]) ([] : List (Option TrioSeq)) (RawU_nil 1) (by simp [NoTie]) (WordsG_nil 1))) rfl))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h

/-- ★ シート行 1422。 -/
theorem R1422_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 1, 0), (1, 1, 0), (2, 2, 1), (3, 2, 1), (3, 2, 0), (2, 2, 0), (3, 3, 1), (4, 3, 1), (4, 2, 0)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_hang (starOK_topFarTie (v := 0) ([] : List (List (Option TrioSeq))) (RawUs_nil 0) (by simp [NoTie]) ([] : List (Option TrioSeq)) (RawU_nil 0) (by simp [NoTie]) (WordsG_nil 0)) (Wg_of_starOK (starOK_hang (starOK_topFarTie (v := 1) ([] : List (List (Option TrioSeq))) (RawUs_nil 1) (by simp [NoTie]) ([] : List (Option TrioSeq)) (RawU_nil 1) (by simp [NoTie]) (WordsG_nil 1)) (Wg_of_starOK (starOK_topFar (v := 2) ([([some ([(0, 2, 0)] : TrioSeq)] : List (Option TrioSeq))] : List (List (Option TrioSeq))) (RawUs_cons (RawU_cons_some (show ([(0, 2, 0)] : TrioSeq) ∈ Wg (2 * 2) by have h := Wg_up (w := 2 * 2) (Wg_of_starOK (starOK_wordsG (v := 2) (WordsG_nil 2))) (by omega); simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h) rfl (RawU_nil 2)) (RawUs_nil 2)) (by simp [NoTie]) (WordsG_nil 2))) rfl)) rfl))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h

/-- ★ シート行 1423。 -/
theorem R1423_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 1, 0), (1, 1, 0), (2, 2, 1), (3, 2, 1), (3, 2, 0), (2, 2, 0), (3, 3, 1), (4, 3, 1), (4, 2, 0), (3, 3, 1), (4, 3, 1)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_hang (starOK_topFarTie (v := 0) ([] : List (List (Option TrioSeq))) (RawUs_nil 0) (by simp [NoTie]) ([] : List (Option TrioSeq)) (RawU_nil 0) (by simp [NoTie]) (WordsG_nil 0)) (Wg_of_starOK (starOK_hang (starOK_topFarTie (v := 1) ([] : List (List (Option TrioSeq))) (RawUs_nil 1) (by simp [NoTie]) ([] : List (Option TrioSeq)) (RawU_nil 1) (by simp [NoTie]) (WordsG_nil 1)) (Wg_of_starOK (starOK_topFar (v := 2) ([([some ([(0, 2, 0)] : TrioSeq)] : List (Option TrioSeq)), ([] : List (Option TrioSeq))] : List (List (Option TrioSeq))) (RawUs_cons (RawU_cons_some (show ([(0, 2, 0)] : TrioSeq) ∈ Wg (2 * 2) by have h := Wg_up (w := 2 * 2) (Wg_of_starOK (starOK_wordsG (v := 2) (WordsG_nil 2))) (by omega); simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h) rfl (RawU_nil 2)) (RawUs_cons (RawU_nil 2) (RawUs_nil 2))) (by simp [NoTie]) (WordsG_nil 2))) rfl)) rfl))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h

/-- ★ シート行 1424。 -/
theorem R1424_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 1, 0), (1, 1, 0), (2, 2, 1), (3, 2, 1), (3, 2, 0), (2, 2, 0), (3, 3, 1), (4, 3, 1), (4, 2, 0), (4, 2, 0)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_hang (starOK_topFarTie (v := 0) ([] : List (List (Option TrioSeq))) (RawUs_nil 0) (by simp [NoTie]) ([] : List (Option TrioSeq)) (RawU_nil 0) (by simp [NoTie]) (WordsG_nil 0)) (Wg_of_starOK (starOK_hang (starOK_topFarTie (v := 1) ([] : List (List (Option TrioSeq))) (RawUs_nil 1) (by simp [NoTie]) ([] : List (Option TrioSeq)) (RawU_nil 1) (by simp [NoTie]) (WordsG_nil 1)) (Wg_of_starOK (starOK_topFar (v := 2) ([([some ([(0, 2, 0)] : TrioSeq), some ([(0, 2, 0)] : TrioSeq)] : List (Option TrioSeq))] : List (List (Option TrioSeq))) (RawUs_cons (RawU_cons_some (show ([(0, 2, 0)] : TrioSeq) ∈ Wg (2 * 2) by have h := Wg_up (w := 2 * 2) (Wg_of_starOK (starOK_wordsG (v := 2) (WordsG_nil 2))) (by omega); simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h) rfl (RawU_cons_some (show ([(0, 2, 0)] : TrioSeq) ∈ Wg (2 * 2) by have h := Wg_up (w := 2 * 2) (Wg_of_starOK (starOK_wordsG (v := 2) (WordsG_nil 2))) (by omega); simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h) rfl (RawU_nil 2))) (RawUs_nil 2)) (by simp [NoTie]) (WordsG_nil 2))) rfl)) rfl))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h

/-- ★ シート行 1425。 -/
theorem R1425_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 1, 0), (1, 1, 0), (2, 2, 1), (3, 2, 1), (3, 2, 0), (2, 2, 0), (3, 3, 1), (4, 3, 1), (4, 3, 0)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_hang (starOK_topFarTie (v := 0) ([] : List (List (Option TrioSeq))) (RawUs_nil 0) (by simp [NoTie]) ([] : List (Option TrioSeq)) (RawU_nil 0) (by simp [NoTie]) (WordsG_nil 0)) (Wg_of_starOK (starOK_hang (starOK_topFarTie (v := 1) ([] : List (List (Option TrioSeq))) (RawUs_nil 1) (by simp [NoTie]) ([] : List (Option TrioSeq)) (RawU_nil 1) (by simp [NoTie]) (WordsG_nil 1)) (Wg_of_starOK (starOK_topFarTie (v := 2) ([] : List (List (Option TrioSeq))) (RawUs_nil 2) (by simp [NoTie]) ([] : List (Option TrioSeq)) (RawU_nil 2) (by simp [NoTie]) (WordsG_nil 2))) rfl)) rfl))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h

/-- ★ シート行 1426。 -/
theorem R1426_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 1, 0), (1, 1, 0), (2, 2, 1), (3, 2, 1), (3, 2, 0), (2, 2, 0), (3, 3, 1), (4, 3, 1), (4, 3, 0), (3, 3, 0), (4, 4, 1), (5, 4, 1), (5, 4, 0)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_hang (starOK_topFarTie (v := 0) ([] : List (List (Option TrioSeq))) (RawUs_nil 0) (by simp [NoTie]) ([] : List (Option TrioSeq)) (RawU_nil 0) (by simp [NoTie]) (WordsG_nil 0)) (Wg_of_starOK (starOK_hang (starOK_topFarTie (v := 1) ([] : List (List (Option TrioSeq))) (RawUs_nil 1) (by simp [NoTie]) ([] : List (Option TrioSeq)) (RawU_nil 1) (by simp [NoTie]) (WordsG_nil 1)) (Wg_of_starOK (starOK_hang (starOK_topFarTie (v := 2) ([] : List (List (Option TrioSeq))) (RawUs_nil 2) (by simp [NoTie]) ([] : List (Option TrioSeq)) (RawU_nil 2) (by simp [NoTie]) (WordsG_nil 2)) (Wg_of_starOK (starOK_topFarTie (v := 3) ([] : List (List (Option TrioSeq))) (RawUs_nil 3) (by simp [NoTie]) ([] : List (Option TrioSeq)) (RawU_nil 3) (by simp [NoTie]) (WordsG_nil 3))) rfl)) rfl)) rfl))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h

/-- ★ シート行 1427。 -/
theorem R1427_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 1, 0), (1, 1, 1)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_topFarTie (v := 0) ([] : List (List (Option TrioSeq))) (RawUs_nil 0) (by simp [NoTie]) ([] : List (Option TrioSeq)) (RawU_nil 0) (by simp [NoTie]) (WordsG_consT (v := 0) (TF_nil 0) (WordsG_nil 0))))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h

/-- ★ シート行 1428。 -/
theorem R1428_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 1, 0), (1, 1, 1), (1, 1, 1)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_topFarTie (v := 0) ([] : List (List (Option TrioSeq))) (RawUs_nil 0) (by simp [NoTie]) ([] : List (Option TrioSeq)) (RawU_nil 0) (by simp [NoTie]) (WordsG_consT (v := 0) (TF_nil 0) (WordsG_consT (v := 0) (TF_nil 0) (WordsG_nil 0)))))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h

/-- ★ シート行 1429。 -/
theorem R1429_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 1, 0), (1, 1, 1), (2, 1, 0)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_topFarTie (v := 0) ([] : List (List (Option TrioSeq))) (RawUs_nil 0) (by simp [NoTie]) ([] : List (Option TrioSeq)) (RawU_nil 0) (by simp [NoTie]) (WordsG_consT (v := 0) (TF_tieG (u := 0) (TF_nil 0) (GF_of_GPF (GPF_nil1 0))) (WordsG_nil 0))))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h

/-- ★ シート行 1430。 -/
theorem R1430_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 1, 0), (1, 1, 1), (2, 1, 0), (3, 2, 0)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_topFarTie (v := 0) ([] : List (List (Option TrioSeq))) (RawUs_nil 0) (by simp [NoTie]) ([] : List (Option TrioSeq)) (RawU_nil 0) (by simp [NoTie]) (WordsG_consT (v := 0) (TF_tieG (u := 0) (TF_nil 0) (GF_of_GPF (GPF_node (A := []) (o := 1) (by decide) (by decide) (by decide) (b := 0) (τ := 2) [] (by decide) (GPF_nil1 0) (GPF_nil (A := []) (o := 2) (by decide) (by decide) 0)))) (WordsG_nil 0))))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h

/-- ★ シート行 1431。 -/
theorem R1431_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 1, 0), (1, 1, 1), (2, 1, 0), (3, 2, 1)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_topFarTie (v := 0) ([] : List (List (Option TrioSeq))) (RawUs_nil 0) (by simp [NoTie]) ([] : List (Option TrioSeq)) (RawU_nil 0) (by simp [NoTie]) (WordsG_consT (v := 0) (TF_tieG (u := 0) (TF_nil 0) (GF_of_GPF (GPF_of_PVF (PVF_snoc (A := []) (o := 1) (by decide) (PVF_nil1 0) (RLF_nil (A := []) (o := 1) (by decide) (by decide) (by decide) 0))))) (WordsG_nil 0))))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h

/-- ★ シート行 1432。 -/
theorem R1432_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 1, 0), (1, 1, 1), (2, 1, 0), (3, 2, 1), (4, 2, 1)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_topFarTie (v := 0) ([] : List (List (Option TrioSeq))) (RawUs_nil 0) (by simp [NoTie]) ([] : List (Option TrioSeq)) (RawU_nil 0) (by simp [NoTie]) (WordsG_consT (v := 0) (TF_tieG (u := 0) (TF_nil 0) (GF_of_GPF (GPF_of_PVF (PVF_farU (A := []) (o := 1) (by decide) (by decide) (by decide) 0 ([([] : List (Option TrioSeq))] : List (List (Option TrioSeq))) (RawUs_cons (RawU_nil 0) (RawUs_nil 0)))))) (WordsG_nil 0))))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h

/-- ★ シート行 1433。 -/
theorem R1433_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 1, 0), (1, 1, 1), (2, 1, 0), (3, 2, 1), (4, 2, 1)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_topFarTie (v := 0) ([] : List (List (Option TrioSeq))) (RawUs_nil 0) (by simp [NoTie]) ([] : List (Option TrioSeq)) (RawU_nil 0) (by simp [NoTie]) (WordsG_consT (v := 0) (TF_tieG (u := 0) (TF_nil 0) (GF_of_GPF (GPF_of_PVF (PVF_farU (A := []) (o := 1) (by decide) (by decide) (by decide) 0 ([([] : List (Option TrioSeq))] : List (List (Option TrioSeq))) (RawUs_cons (RawU_nil 0) (RawUs_nil 0)))))) (WordsG_nil 0))))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h

/-- ★ シート行 1434。 -/
theorem R1434_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 1, 0), (1, 1, 1), (2, 1, 0), (3, 2, 1), (4, 2, 1), (4, 1, 0), (1, 1, 1)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_topFarTie (v := 0) ([] : List (List (Option TrioSeq))) (RawUs_nil 0) (by simp [NoTie]) ([] : List (Option TrioSeq)) (RawU_nil 0) (by simp [NoTie]) (WordsG_consT (v := 0) (TF_tieG (u := 0) (TF_nil 0) (GF_of_GPF (GPF_of_PVF (PVF_farU (A := []) (o := 1) (by decide) (by decide) (by decide) 0 ([([none] : List (Option TrioSeq))] : List (List (Option TrioSeq))) (RawUs_cons (RawU_cons_none (RawU_nil 0)) (RawUs_nil 0)))))) (WordsG_consT (v := 0) (TF_nil 0) (WordsG_nil 0)))))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h

/-- ★ シート行 1435。 -/
theorem R1435_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 1, 0), (1, 1, 1), (2, 1, 0), (3, 2, 1), (4, 2, 1), (4, 1, 0), (1, 1, 1), (2, 1, 0), (3, 2, 1), (4, 2, 1), (4, 1, 0), (1, 1, 1)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_topFarTie (v := 0) ([] : List (List (Option TrioSeq))) (RawUs_nil 0) (by simp [NoTie]) ([] : List (Option TrioSeq)) (RawU_nil 0) (by simp [NoTie]) (WordsG_consT (v := 0) (TF_tieG (u := 0) (TF_nil 0) (GF_of_GPF (GPF_of_PVF (PVF_farU (A := []) (o := 1) (by decide) (by decide) (by decide) 0 ([([none] : List (Option TrioSeq))] : List (List (Option TrioSeq))) (RawUs_cons (RawU_cons_none (RawU_nil 0)) (RawUs_nil 0)))))) (WordsG_consT (v := 0) (TF_tieG (u := 0) (TF_nil 0) (GF_of_GPF (GPF_of_PVF (PVF_farU (A := []) (o := 1) (by decide) (by decide) (by decide) 0 ([([none] : List (Option TrioSeq))] : List (List (Option TrioSeq))) (RawUs_cons (RawU_cons_none (RawU_nil 0)) (RawUs_nil 0)))))) (WordsG_consT (v := 0) (TF_nil 0) (WordsG_nil 0))))))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h

/-- ★ シート行 1436。 -/
theorem R1436_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 1, 0), (1, 1, 1), (2, 1, 0), (3, 2, 1), (4, 2, 1), (4, 1, 0), (2, 1, 0), (1, 1, 1)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_topFarTie (v := 0) ([] : List (List (Option TrioSeq))) (RawUs_nil 0) (by simp [NoTie]) ([] : List (Option TrioSeq)) (RawU_nil 0) (by simp [NoTie]) (WordsG_consT (v := 0) (TF_tieG (u := 0) (TF_tieG (u := 0) (TF_nil 0) (GF_of_GPF (GPF_of_PVF (PVF_farU (A := []) (o := 1) (by decide) (by decide) (by decide) 0 ([([none] : List (Option TrioSeq))] : List (List (Option TrioSeq))) (RawUs_cons (RawU_cons_none (RawU_nil 0)) (RawUs_nil 0)))))) (GF_of_GPF (GPF_nil1 0))) (WordsG_consT (v := 0) (TF_nil 0) (WordsG_nil 0)))))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h

/-- ★ シート行 1437。 -/
theorem R1437_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 1, 0), (1, 1, 1), (2, 1, 0), (3, 2, 1), (4, 2, 1), (4, 1, 0), (3, 1, 0), (1, 1, 1)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_topFarTie (v := 0) ([] : List (List (Option TrioSeq))) (RawUs_nil 0) (by simp [NoTie]) ([] : List (Option TrioSeq)) (RawU_nil 0) (by simp [NoTie]) (WordsG_consT (v := 0) (TF_tieG (u := 0) (TF_nil 0) (GF_of_GPF (GPF_node (A := []) (o := 1) (by decide) (by decide) (by decide) (b := 0) (τ := 1) [] (by decide) (GPF_of_PVF (PVF_farU (A := []) (o := 1) (by decide) (by decide) (by decide) 0 ([([none] : List (Option TrioSeq))] : List (List (Option TrioSeq))) (RawUs_cons (RawU_cons_none (RawU_nil 0)) (RawUs_nil 0)))) (GPF_nil1 0)))) (WordsG_consT (v := 0) (TF_nil 0) (WordsG_nil 0)))))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h

/-- ★ シート行 1438。 -/
theorem R1438_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 1, 0), (1, 1, 1), (2, 1, 0), (3, 2, 1), (4, 2, 1), (4, 1, 0), (3, 2, 0)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_topFarTie (v := 0) ([] : List (List (Option TrioSeq))) (RawUs_nil 0) (by simp [NoTie]) ([] : List (Option TrioSeq)) (RawU_nil 0) (by simp [NoTie]) (WordsG_consT (v := 0) (TF_tieG (u := 0) (TF_nil 0) (GF_of_GPF (GPF_node (A := []) (o := 1) (by decide) (by decide) (by decide) (b := 0) (τ := 2) [] (by decide) (GPF_of_PVF (PVF_farU (A := []) (o := 1) (by decide) (by decide) (by decide) 0 ([([none] : List (Option TrioSeq))] : List (List (Option TrioSeq))) (RawUs_cons (RawU_cons_none (RawU_nil 0)) (RawUs_nil 0)))) (GPF_nil (A := []) (o := 2) (by decide) (by decide) 0)))) (WordsG_nil 0))))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h

/-- ★ シート行 1439。 -/
theorem R1439_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 1, 0), (1, 1, 1), (2, 1, 0), (3, 2, 1), (4, 2, 1), (4, 1, 0), (3, 2, 0), (4, 3, 1), (5, 3, 1), (5, 1, 0)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_topFarTie (v := 0) ([] : List (List (Option TrioSeq))) (RawUs_nil 0) (by simp [NoTie]) ([] : List (Option TrioSeq)) (RawU_nil 0) (by simp [NoTie]) (WordsG_consT (v := 0) (TF_tieG (u := 0) (TF_nil 0) (GF_of_GPF (GPF_node (A := []) (o := 1) (by decide) (by decide) (by decide) (b := 0) (τ := 2) [] (by decide) (GPF_of_PVF (PVF_farU (A := []) (o := 1) (by decide) (by decide) (by decide) 0 ([([none] : List (Option TrioSeq))] : List (List (Option TrioSeq))) (RawUs_cons (RawU_cons_none (RawU_nil 0)) (RawUs_nil 0)))) (GPF_of_PVF (PVF_farU (A := []) (o := 2) (by decide) (by decide) (by decide) 0 ([([none] : List (Option TrioSeq))] : List (List (Option TrioSeq))) (RawUs_cons (RawU_cons_none (RawU_nil 0)) (RawUs_nil 0))))))) (WordsG_nil 0))))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h

/-- ★ シート行 1440。 -/
theorem R1440_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 1, 0), (1, 1, 1), (2, 1, 0), (3, 2, 1), (4, 2, 1), (4, 1, 0), (3, 2, 0), (4, 3, 1), (5, 3, 1), (5, 1, 0), (4, 3, 0)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_topFarTie (v := 0) ([] : List (List (Option TrioSeq))) (RawUs_nil 0) (by simp [NoTie]) ([] : List (Option TrioSeq)) (RawU_nil 0) (by simp [NoTie]) (WordsG_consT (v := 0) (TF_tieG (u := 0) (TF_nil 0) (GF_of_GPF (GPF_node (A := []) (o := 1) (by decide) (by decide) (by decide) (b := 0) (τ := 2) [] (by decide) (GPF_of_PVF (PVF_farU (A := []) (o := 1) (by decide) (by decide) (by decide) 0 ([([none] : List (Option TrioSeq))] : List (List (Option TrioSeq))) (RawUs_cons (RawU_cons_none (RawU_nil 0)) (RawUs_nil 0)))) (GPF_node (A := []) (o := 2) (by decide) (by decide) (by decide) (b := 0) (τ := 3) [] (by decide) (GPF_of_PVF (PVF_farU (A := []) (o := 2) (by decide) (by decide) (by decide) 0 ([([none] : List (Option TrioSeq))] : List (List (Option TrioSeq))) (RawUs_cons (RawU_cons_none (RawU_nil 0)) (RawUs_nil 0)))) (GPF_nil (A := []) (o := 3) (by decide) (by decide) 0))))) (WordsG_nil 0))))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h

/-- ★ シート行 1441。 -/
theorem R1441_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 1, 0), (1, 1, 1), (2, 1, 0), (3, 2, 1), (4, 2, 1), (4, 1, 0), (3, 2, 1)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_topFarTie (v := 0) ([] : List (List (Option TrioSeq))) (RawUs_nil 0) (by simp [NoTie]) ([] : List (Option TrioSeq)) (RawU_nil 0) (by simp [NoTie]) (WordsG_consT (v := 0) (TF_tieG (u := 0) (TF_nil 0) (GF_of_GPF (GPF_of_PVF (PVF_snoc (A := []) (o := 1) (by decide) (PVF_farU (A := []) (o := 1) (by decide) (by decide) (by decide) 0 ([([none] : List (Option TrioSeq))] : List (List (Option TrioSeq))) (RawUs_cons (RawU_cons_none (RawU_nil 0)) (RawUs_nil 0))) (RLF_nil (A := []) (o := 1) (by decide) (by decide) (by decide) 0))))) (WordsG_nil 0))))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h

/-- ★ シート行 1442。 -/
theorem R1442_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 1, 0), (1, 1, 1), (2, 1, 0), (3, 2, 1), (4, 2, 1), (4, 1, 0), (3, 2, 1), (4, 2, 0), (5, 3, 1), (6, 3, 1)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_topFarTie (v := 0) ([] : List (List (Option TrioSeq))) (RawUs_nil 0) (by simp [NoTie]) ([] : List (Option TrioSeq)) (RawU_nil 0) (by simp [NoTie]) (WordsG_consT (v := 0) (TF_tieG (u := 0) (TF_nil 0) (GF_of_GPF (GPF_of_PVF (PVF_snoc (A := []) (o := 1) (by decide) (PVF_farU (A := []) (o := 1) (by decide) (by decide) (by decide) 0 ([([none] : List (Option TrioSeq))] : List (List (Option TrioSeq))) (RawUs_cons (RawU_cons_none (RawU_nil 0)) (RawUs_nil 0))) (RLF_child (A := []) (o := 1) (by decide) (by decide) (by decide) (b := 0) (τ := 2) [1] (by decide) (by decide) (RLF_nil (A := []) (o := 1) (by decide) (by decide) (by decide) 0) (GPF_of_PVF (PVF_farU (A := [1]) (o := 2) (by decide) (by decide) (by decide) 0 ([([] : List (Option TrioSeq))] : List (List (Option TrioSeq))) (RawUs_cons (RawU_nil 0) (RawUs_nil 0))))))))) (WordsG_nil 0))))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h

/-- ★ シート行 1443。 -/
theorem R1443_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 1, 0), (1, 1, 1), (2, 1, 0), (3, 2, 1), (4, 2, 1), (4, 1, 0), (3, 2, 1), (4, 2, 0), (5, 3, 1), (6, 3, 1), (6, 1, 0), (5, 3, 0)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_topFarTie (v := 0) ([] : List (List (Option TrioSeq))) (RawUs_nil 0) (by simp [NoTie]) ([] : List (Option TrioSeq)) (RawU_nil 0) (by simp [NoTie]) (WordsG_consT (v := 0) (TF_tieG (u := 0) (TF_nil 0) (GF_of_GPF (GPF_of_PVF (PVF_snoc (A := []) (o := 1) (by decide) (PVF_farU (A := []) (o := 1) (by decide) (by decide) (by decide) 0 ([([none] : List (Option TrioSeq))] : List (List (Option TrioSeq))) (RawUs_cons (RawU_cons_none (RawU_nil 0)) (RawUs_nil 0))) (RLF_child (A := []) (o := 1) (by decide) (by decide) (by decide) (b := 0) (τ := 2) [1] (by decide) (by decide) (RLF_nil (A := []) (o := 1) (by decide) (by decide) (by decide) 0) (GPF_node (A := [1]) (o := 2) (by decide) (by decide) (by decide) (b := 0) (τ := 3) [1] (by decide) (GPF_of_PVF (PVF_farU (A := [1]) (o := 2) (by decide) (by decide) (by decide) 0 ([([none] : List (Option TrioSeq))] : List (List (Option TrioSeq))) (RawUs_cons (RawU_cons_none (RawU_nil 0)) (RawUs_nil 0)))) (GPF_nil (A := [1]) (o := 3) (by decide) (by decide) 0))))))) (WordsG_nil 0))))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h

/-- ★ シート行 1444。 -/
theorem R1444_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 1, 0), (1, 1, 1), (2, 1, 0), (3, 2, 1), (4, 2, 1), (4, 1, 0), (3, 2, 1), (4, 2, 0), (5, 3, 1), (6, 3, 1), (6, 1, 0), (5, 3, 1)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_topFarTie (v := 0) ([] : List (List (Option TrioSeq))) (RawUs_nil 0) (by simp [NoTie]) ([] : List (Option TrioSeq)) (RawU_nil 0) (by simp [NoTie]) (WordsG_consT (v := 0) (TF_tieG (u := 0) (TF_nil 0) (GF_of_GPF (GPF_of_PVF (PVF_snoc (A := []) (o := 1) (by decide) (PVF_farU (A := []) (o := 1) (by decide) (by decide) (by decide) 0 ([([none] : List (Option TrioSeq))] : List (List (Option TrioSeq))) (RawUs_cons (RawU_cons_none (RawU_nil 0)) (RawUs_nil 0))) (RLF_child (A := []) (o := 1) (by decide) (by decide) (by decide) (b := 0) (τ := 2) [1] (by decide) (by decide) (RLF_nil (A := []) (o := 1) (by decide) (by decide) (by decide) 0) (GPF_of_PVF (PVF_snoc (A := [1]) (o := 2) (by decide) (PVF_farU (A := [1]) (o := 2) (by decide) (by decide) (by decide) 0 ([([none] : List (Option TrioSeq))] : List (List (Option TrioSeq))) (RawUs_cons (RawU_cons_none (RawU_nil 0)) (RawUs_nil 0))) (RLF_nil (A := [1]) (o := 2) (by decide) (by decide) (by decide) 0)))))))) (WordsG_nil 0))))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h

/-- ★ シート行 1445。 -/
theorem R1445_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 1, 0), (1, 1, 1), (2, 1, 0), (3, 2, 1), (4, 2, 1), (4, 1, 0), (3, 2, 1), (4, 2, 1)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_topFarTie (v := 0) ([] : List (List (Option TrioSeq))) (RawUs_nil 0) (by simp [NoTie]) ([] : List (Option TrioSeq)) (RawU_nil 0) (by simp [NoTie]) (WordsG_consT (v := 0) (TF_tieG (u := 0) (TF_nil 0) (GF_of_GPF (GPF_of_PVF (PVF_farU (A := []) (o := 1) (by decide) (by decide) (by decide) 0 ([([none] : List (Option TrioSeq)), ([] : List (Option TrioSeq))] : List (List (Option TrioSeq))) (RawUs_cons (RawU_cons_none (RawU_nil 0)) (RawUs_cons (RawU_nil 0) (RawUs_nil 0))))))) (WordsG_nil 0))))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h

/-- ★ シート行 1446。 -/
theorem R1446_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 1, 0), (1, 1, 1), (2, 1, 0), (3, 2, 1), (4, 2, 1), (4, 1, 0), (3, 2, 1), (4, 2, 1), (4, 0, 0)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_topFarTie (v := 0) ([] : List (List (Option TrioSeq))) (RawUs_nil 0) (by simp [NoTie]) ([] : List (Option TrioSeq)) (RawU_nil 0) (by simp [NoTie]) (WordsG_consT (v := 0) (TF_tieG (u := 0) (TF_nil 0) (GF_of_GPF (GPF_of_PVF (PVF_farU (A := []) (o := 1) (by decide) (by decide) (by decide) 0 ([([none] : List (Option TrioSeq)), ([some ([(0, 0, 0)] : TrioSeq)] : List (Option TrioSeq))] : List (List (Option TrioSeq))) (RawUs_cons (RawU_cons_none (RawU_nil 0)) (RawUs_cons (RawU_cons_some (show ([(0, 0, 0)] : TrioSeq) ∈ Wg (2 * 0) by have h := Wg_up (w := 2 * 0) (Wg_of_starOK (starOK_wordsG (v := 0) (WordsG_nil 0))) (by omega); simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h) rfl (RawU_nil 0)) (RawUs_nil 0))))))) (WordsG_nil 0))))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h

/-- ★ シート行 1447。 -/
theorem R1447_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 1, 0), (1, 1, 1), (2, 1, 0), (3, 2, 1), (4, 2, 1), (4, 1, 0), (3, 2, 1), (4, 2, 1), (4, 1, 0)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_topFarTie (v := 0) ([] : List (List (Option TrioSeq))) (RawUs_nil 0) (by simp [NoTie]) ([] : List (Option TrioSeq)) (RawU_nil 0) (by simp [NoTie]) (WordsG_consT (v := 0) (TF_tieG (u := 0) (TF_nil 0) (GF_of_GPF (GPF_of_PVF (PVF_farU (A := []) (o := 1) (by decide) (by decide) (by decide) 0 ([([none] : List (Option TrioSeq)), ([none] : List (Option TrioSeq))] : List (List (Option TrioSeq))) (RawUs_cons (RawU_cons_none (RawU_nil 0)) (RawUs_cons (RawU_cons_none (RawU_nil 0)) (RawUs_nil 0))))))) (WordsG_nil 0))))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h

/-- ★ シート行 1448。 -/
theorem R1448_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 1, 0), (1, 1, 1), (2, 1, 0), (3, 2, 1), (4, 2, 1), (4, 1, 0), (3, 2, 1), (4, 2, 1), (4, 1, 0), (1, 1, 1)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_topFarTie (v := 0) ([] : List (List (Option TrioSeq))) (RawUs_nil 0) (by simp [NoTie]) ([] : List (Option TrioSeq)) (RawU_nil 0) (by simp [NoTie]) (WordsG_consT (v := 0) (TF_tieG (u := 0) (TF_nil 0) (GF_of_GPF (GPF_of_PVF (PVF_farU (A := []) (o := 1) (by decide) (by decide) (by decide) 0 ([([none] : List (Option TrioSeq)), ([none] : List (Option TrioSeq))] : List (List (Option TrioSeq))) (RawUs_cons (RawU_cons_none (RawU_nil 0)) (RawUs_cons (RawU_cons_none (RawU_nil 0)) (RawUs_nil 0))))))) (WordsG_consT (v := 0) (TF_nil 0) (WordsG_nil 0)))))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h

/-- ★ シート行 1449。 -/
theorem R1449_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 1, 0), (1, 1, 1), (2, 1, 0), (3, 2, 1), (4, 2, 1), (4, 1, 0), (4, 1, 0), (1, 1, 1)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_topFarTie (v := 0) ([] : List (List (Option TrioSeq))) (RawUs_nil 0) (by simp [NoTie]) ([] : List (Option TrioSeq)) (RawU_nil 0) (by simp [NoTie]) (WordsG_consT (v := 0) (TF_tieG (u := 0) (TF_nil 0) (GF_of_GPF (GPF_of_PVF (PVF_farU (A := []) (o := 1) (by decide) (by decide) (by decide) 0 ([([none, none] : List (Option TrioSeq))] : List (List (Option TrioSeq))) (RawUs_cons (RawU_cons_none (RawU_cons_none (RawU_nil 0))) (RawUs_nil 0)))))) (WordsG_consT (v := 0) (TF_nil 0) (WordsG_nil 0)))))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop] using h

end GzK
end TRIO
