/-
HaH.lean: tools/gen_gyk.py が生成。錨の列つきの子の述語で証明するシート行。
-/
import GzJ
import GzS
import HaG

namespace TRIO
namespace HaH

open Wset Small GwS Gw GwU GwZ GxD GxG GxJ GxK GxL GxN GxP GxR GxT GxV GxW GxY
open GyA GyB GyC GyD GyE GyF GyG GyH GyI GyJ GyK GzD GzF GzH GzI GzJ GzM GzN GzP GzS GzU GzV GzW GzY HaA HaC HaD HaE HaF HaG

/-- ★ シート行 1479。 -/
theorem R1479_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 1, 0), (1, 1, 1), (2, 1, 0), (3, 2, 1), (4, 2, 1), (4, 2, 0), (3, 2, 1), (4, 2, 0), (5, 3, 1), (6, 3, 1), (6, 2, 0), (5, 3, 1), (6, 3, 1)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_topFarTie (v := 0) ([] : List (List (Option TrioSeq))) (RawUs_nil 0) (by simp [NoTie]) ([] : List (Option TrioSeq)) (RawU_nil 0) (by simp [NoTie]) (WordsG_consT (v := 0) (TF_tieG (u := 0) (TF_nil 0) (GF_of_GPF (GPF_of_PVF (PVF_snoc (A := []) (o := 1) (by decide) (PVF_farW_Fr (o := 1) (by decide) le_rfl (fun k hk => (OkWsk_nil k 0)) (fun k hk => (okWkF_nil k 0))) (RLF_child (A := []) (o := 1) (by decide) (by decide) (by decide) (b := 0) (τ := 2) [1] (by decide) (by decide) (RLF_nil (A := []) (o := 1) (by decide) (by decide) (by decide) 0) (GPF_of_PVF (PVF_farWA (A0 := [1]) (o := 2) (by decide) (by decide) (by decide) 0 _ (OkWsA_cons le_rfl (okRA_node (A0 := [1]) (o := 2) (τ := 2) (by decide) (by decide) (by decide) (by decide) [1] (by decide) (okRA_nil [1] 2 0) (GPF_nil (A := [1]) (o := 2) (by decide) (by decide) 0)) (OkWsA_cons le_rfl (okRA_nil [1] 2 0) (OkWsA_nil [1] 2 0)))))))))) (WordsG_nil 0))))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop, farW, fwW, mlift_zero, Nat.sub_self] using h

/-- ★ シート行 1480。 -/
theorem R1480_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 1, 0), (1, 1, 1), (2, 1, 0), (3, 2, 1), (4, 2, 1), (4, 2, 0), (3, 2, 1), (4, 2, 0), (5, 3, 1), (6, 3, 1), (6, 2, 0), (5, 3, 1), (6, 3, 1), (6, 2, 0)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_topFarTie (v := 0) ([] : List (List (Option TrioSeq))) (RawUs_nil 0) (by simp [NoTie]) ([] : List (Option TrioSeq)) (RawU_nil 0) (by simp [NoTie]) (WordsG_consT (v := 0) (TF_tieG (u := 0) (TF_nil 0) (GF_of_GPF (GPF_of_PVF (PVF_snoc (A := []) (o := 1) (by decide) (PVF_farW_Fr (o := 1) (by decide) le_rfl (fun k hk => (OkWsk_nil k 0)) (fun k hk => (okWkF_nil k 0))) (RLF_child (A := []) (o := 1) (by decide) (by decide) (by decide) (b := 0) (τ := 2) [1] (by decide) (by decide) (RLF_nil (A := []) (o := 1) (by decide) (by decide) (by decide) 0) (GPF_of_PVF (PVF_farWA (A0 := [1]) (o := 2) (by decide) (by decide) (by decide) 0 _ (OkWsA_cons le_rfl (okRA_node (A0 := [1]) (o := 2) (τ := 2) (by decide) (by decide) (by decide) (by decide) [1] (by decide) (okRA_nil [1] 2 0) (GPF_nil (A := [1]) (o := 2) (by decide) (by decide) 0)) (OkWsA_cons le_rfl (okRA_node (A0 := [1]) (o := 2) (τ := 2) (by decide) (by decide) (by decide) (by decide) [1] (by decide) (okRA_nil [1] 2 0) (GPF_nil (A := [1]) (o := 2) (by decide) (by decide) 0)) (OkWsA_nil [1] 2 0)))))))))) (WordsG_nil 0))))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop, farW, fwW, mlift_zero, Nat.sub_self] using h

/-- ★ シート行 1481。 -/
theorem R1481_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 1, 0), (1, 1, 1), (2, 1, 0), (3, 2, 1), (4, 2, 1), (4, 2, 0), (3, 2, 1), (4, 2, 0), (5, 3, 1), (6, 3, 1), (6, 2, 0), (5, 3, 1), (6, 3, 1), (6, 2, 0), (3, 2, 1)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_topFarTie (v := 0) ([] : List (List (Option TrioSeq))) (RawUs_nil 0) (by simp [NoTie]) ([] : List (Option TrioSeq)) (RawU_nil 0) (by simp [NoTie]) (WordsG_consT (v := 0) (TF_tieG (u := 0) (TF_nil 0) (GF_of_GPF (GPF_of_PVF (PVF_snoc (A := []) (o := 1) (by decide) (PVF_snoc (A := []) (o := 1) (by decide) (PVF_farW_Fr (o := 1) (by decide) le_rfl (fun k hk => (OkWsk_nil k 0)) (fun k hk => (okWkF_nil k 0))) (RLF_child (A := []) (o := 1) (by decide) (by decide) (by decide) (b := 0) (τ := 2) [1] (by decide) (by decide) (RLF_nil (A := []) (o := 1) (by decide) (by decide) (by decide) 0) (GPF_of_PVF (PVF_farWA (A0 := [1]) (o := 2) (by decide) (by decide) (by decide) 0 _ (OkWsA_cons le_rfl (okRA_node (A0 := [1]) (o := 2) (τ := 2) (by decide) (by decide) (by decide) (by decide) [1] (by decide) (okRA_nil [1] 2 0) (GPF_nil (A := [1]) (o := 2) (by decide) (by decide) 0)) (OkWsA_cons le_rfl (okRA_node (A0 := [1]) (o := 2) (τ := 2) (by decide) (by decide) (by decide) (by decide) [1] (by decide) (okRA_nil [1] 2 0) (GPF_nil (A := [1]) (o := 2) (by decide) (by decide) 0)) (OkWsA_nil [1] 2 0))))))) (RLF_nil (A := []) (o := 1) (by decide) (by decide) (by decide) 0))))) (WordsG_nil 0))))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop, farW, fwW, mlift_zero, Nat.sub_self] using h

/-- ★ シート行 1482。 -/
theorem R1482_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 1, 0), (1, 1, 1), (2, 1, 0), (3, 2, 1), (4, 2, 1), (4, 2, 0), (3, 2, 1), (4, 2, 0), (5, 3, 1), (6, 3, 1), (6, 2, 0), (6, 2, 0), (3, 2, 1)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_topFarTie (v := 0) ([] : List (List (Option TrioSeq))) (RawUs_nil 0) (by simp [NoTie]) ([] : List (Option TrioSeq)) (RawU_nil 0) (by simp [NoTie]) (WordsG_consT (v := 0) (TF_tieG (u := 0) (TF_nil 0) (GF_of_GPF (GPF_of_PVF (PVF_snoc (A := []) (o := 1) (by decide) (PVF_snoc (A := []) (o := 1) (by decide) (PVF_farW_Fr (o := 1) (by decide) le_rfl (fun k hk => (OkWsk_nil k 0)) (fun k hk => (okWkF_nil k 0))) (RLF_child (A := []) (o := 1) (by decide) (by decide) (by decide) (b := 0) (τ := 2) [1] (by decide) (by decide) (RLF_nil (A := []) (o := 1) (by decide) (by decide) (by decide) 0) (GPF_of_PVF (PVF_farWA (A0 := [1]) (o := 2) (by decide) (by decide) (by decide) 0 _ (OkWsA_cons le_rfl (okRA_node (A0 := [1]) (o := 2) (τ := 2) (by decide) (by decide) (by decide) (by decide) [1] (by decide) (okRA_node (A0 := [1]) (o := 2) (τ := 2) (by decide) (by decide) (by decide) (by decide) [1] (by decide) (okRA_nil [1] 2 0) (GPF_nil (A := [1]) (o := 2) (by decide) (by decide) 0)) (GPF_nil (A := [1]) (o := 2) (by decide) (by decide) 0)) (OkWsA_nil [1] 2 0)))))) (RLF_nil (A := []) (o := 1) (by decide) (by decide) (by decide) 0))))) (WordsG_nil 0))))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop, farW, fwW, mlift_zero, Nat.sub_self] using h

/-- ★ シート行 1483。 -/
theorem R1483_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 1, 0), (1, 1, 1), (2, 1, 0), (3, 2, 1), (4, 2, 1), (4, 2, 0), (3, 2, 1), (4, 2, 0), (5, 3, 1), (6, 3, 1), (6, 2, 0), (7, 3, 0)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_topFarTie (v := 0) ([] : List (List (Option TrioSeq))) (RawUs_nil 0) (by simp [NoTie]) ([] : List (Option TrioSeq)) (RawU_nil 0) (by simp [NoTie]) (WordsG_consT (v := 0) (TF_tieG (u := 0) (TF_nil 0) (GF_of_GPF (GPF_of_PVF (PVF_snoc (A := []) (o := 1) (by decide) (PVF_farW_Fr (o := 1) (by decide) le_rfl (fun k hk => (OkWsk_nil k 0)) (fun k hk => (okWkF_nil k 0))) (RLF_child (A := []) (o := 1) (by decide) (by decide) (by decide) (b := 0) (τ := 2) [1] (by decide) (by decide) (RLF_nil (A := []) (o := 1) (by decide) (by decide) (by decide) 0) (GPF_of_PVF (PVF_farWA (A0 := [1]) (o := 2) (by decide) (by decide) (by decide) 0 _ (OkWsA_cons le_rfl (okRA_node (A0 := [1]) (o := 2) (τ := 2) (by decide) (by decide) (by decide) (by decide) [1] (by decide) (okRA_nil [1] 2 0) (GPF_node (A := [1]) (o := 2) (by decide) (by decide) (by decide) (b := 0) (τ := 3) [1] (by decide) (GPF_nil (A := [1]) (o := 2) (by decide) (by decide) 0) (GPF_nil (A := [1]) (o := 3) (by decide) (by decide) 0))) (OkWsA_nil [1] 2 0))))))))) (WordsG_nil 0))))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop, farW, fwW, mlift_zero, Nat.sub_self] using h

/-- ★ シート行 1484。 -/
theorem R1484_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 1, 0), (1, 1, 1), (2, 1, 0), (3, 2, 1), (4, 2, 1), (4, 2, 0), (3, 2, 1), (4, 2, 0), (5, 3, 1), (6, 3, 1), (6, 2, 0), (7, 3, 1), (8, 3, 1)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_topFarTie (v := 0) ([] : List (List (Option TrioSeq))) (RawUs_nil 0) (by simp [NoTie]) ([] : List (Option TrioSeq)) (RawU_nil 0) (by simp [NoTie]) (WordsG_consT (v := 0) (TF_tieG (u := 0) (TF_nil 0) (GF_of_GPF (GPF_of_PVF (PVF_snoc (A := []) (o := 1) (by decide) (PVF_farW_Fr (o := 1) (by decide) le_rfl (fun k hk => (OkWsk_nil k 0)) (fun k hk => (okWkF_nil k 0))) (RLF_child (A := []) (o := 1) (by decide) (by decide) (by decide) (b := 0) (τ := 2) [1] (by decide) (by decide) (RLF_nil (A := []) (o := 1) (by decide) (by decide) (by decide) 0) (GPF_of_PVF (PVF_farWA (A0 := [1]) (o := 2) (by decide) (by decide) (by decide) 0 _ (OkWsA_cons le_rfl (okRA_node (A0 := [1]) (o := 2) (τ := 2) (by decide) (by decide) (by decide) (by decide) [1] (by decide) (okRA_nil [1] 2 0) (GPF_of_PVF (PVF_farU (A := [1]) (o := 2) (by decide) (by decide) (by decide) 0 ([([] : List (Option TrioSeq))] : List (List (Option TrioSeq))) (RawUs_cons (RawU_nil 0) (RawUs_nil 0))))) (OkWsA_nil [1] 2 0))))))))) (WordsG_nil 0))))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop, farW, fwW, mlift_zero, Nat.sub_self] using h

/-- ★ シート行 1485。 -/
theorem R1485_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 1, 0), (1, 1, 1), (2, 1, 0), (3, 2, 1), (4, 2, 1), (4, 2, 0), (3, 2, 1), (4, 2, 0), (5, 3, 1), (6, 3, 1), (6, 3, 0)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_topFarTie (v := 0) ([] : List (List (Option TrioSeq))) (RawUs_nil 0) (by simp [NoTie]) ([] : List (Option TrioSeq)) (RawU_nil 0) (by simp [NoTie]) (WordsG_consT (v := 0) (TF_tieG (u := 0) (TF_nil 0) (GF_of_GPF (GPF_of_PVF (PVF_snoc (A := []) (o := 1) (by decide) (PVF_farW_Fr (o := 1) (by decide) le_rfl (fun k hk => (OkWsk_nil k 0)) (fun k hk => (okWkF_nil k 0))) (RLF_child (A := []) (o := 1) (by decide) (by decide) (by decide) (b := 0) (τ := 2) [1] (by decide) (by decide) (RLF_nil (A := []) (o := 1) (by decide) (by decide) (by decide) 0) (GPF_of_PVF (PVF_farWA_F (A0 := [1]) (o := 2) (by decide) (by decide) (by decide) le_rfl (fun k hk => (OkWsA_nil [1] k 0)) (fun k hk => (okRA_nil [1] k 0))))))))) (WordsG_nil 0))))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop, farW, fwW, mlift_zero, Nat.sub_self] using h

/-- ★ シート行 1486。 -/
theorem R1486_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 1, 0), (1, 1, 1), (2, 1, 0), (3, 2, 1), (4, 2, 1), (4, 2, 0), (3, 2, 1), (4, 2, 0), (5, 3, 1), (6, 3, 1), (6, 3, 0), (5, 3, 0), (6, 4, 1), (7, 4, 1), (7, 4, 0)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_topFarTie (v := 0) ([] : List (List (Option TrioSeq))) (RawUs_nil 0) (by simp [NoTie]) ([] : List (Option TrioSeq)) (RawU_nil 0) (by simp [NoTie]) (WordsG_consT (v := 0) (TF_tieG (u := 0) (TF_nil 0) (GF_of_GPF (GPF_of_PVF (PVF_snoc (A := []) (o := 1) (by decide) (PVF_farW_Fr (o := 1) (by decide) le_rfl (fun k hk => (OkWsk_nil k 0)) (fun k hk => (okWkF_nil k 0))) (RLF_child (A := []) (o := 1) (by decide) (by decide) (by decide) (b := 0) (τ := 2) [1] (by decide) (by decide) (RLF_nil (A := []) (o := 1) (by decide) (by decide) (by decide) 0) (GPF_node (A := [1]) (o := 2) (by decide) (by decide) (by decide) (b := 0) (τ := 3) [1] (by decide) (GPF_of_PVF (PVF_farWA_F (A0 := [1]) (o := 2) (by decide) (by decide) (by decide) le_rfl (fun k hk => (OkWsA_nil [1] k 0)) (fun k hk => (okRA_nil [1] k 0)))) (GPF_of_PVF (PVF_farWA_F (A0 := [1]) (o := 3) (by decide) (by decide) (by decide) le_rfl (fun k hk => (OkWsA_nil [1] k 0)) (fun k hk => (okRA_nil [1] k 0)))))))))) (WordsG_nil 0))))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop, farW, fwW, mlift_zero, Nat.sub_self] using h

/-- ★ シート行 1487。 -/
theorem R1487_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 1, 0), (1, 1, 1), (2, 1, 0), (3, 2, 1), (4, 2, 1), (4, 2, 0), (3, 2, 1), (4, 2, 0), (5, 3, 1), (6, 3, 1), (6, 3, 0), (5, 3, 1)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_topFarTie (v := 0) ([] : List (List (Option TrioSeq))) (RawUs_nil 0) (by simp [NoTie]) ([] : List (Option TrioSeq)) (RawU_nil 0) (by simp [NoTie]) (WordsG_consT (v := 0) (TF_tieG (u := 0) (TF_nil 0) (GF_of_GPF (GPF_of_PVF (PVF_snoc (A := []) (o := 1) (by decide) (PVF_farW_Fr (o := 1) (by decide) le_rfl (fun k hk => (OkWsk_nil k 0)) (fun k hk => (okWkF_nil k 0))) (RLF_child (A := []) (o := 1) (by decide) (by decide) (by decide) (b := 0) (τ := 2) [1] (by decide) (by decide) (RLF_nil (A := []) (o := 1) (by decide) (by decide) (by decide) 0) (GPF_of_PVF (PVF_snoc (A := [1]) (o := 2) (by decide) (PVF_farWA_F (A0 := [1]) (o := 2) (by decide) (by decide) (by decide) le_rfl (fun k hk => (OkWsA_nil [1] k 0)) (fun k hk => (okRA_nil [1] k 0))) (RLF_nil (A := [1]) (o := 2) (by decide) (by decide) (by decide) 0)))))))) (WordsG_nil 0))))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop, farW, fwW, mlift_zero, Nat.sub_self] using h

/-- ★ シート行 1488。 -/
theorem R1488_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 1, 0), (1, 1, 1), (2, 1, 0), (3, 2, 1), (4, 2, 1), (4, 2, 0), (3, 2, 1), (4, 2, 0), (5, 3, 1), (6, 3, 1), (6, 3, 0), (5, 3, 1), (6, 3, 0), (7, 4, 1), (8, 4, 1), (8, 4, 0), (7, 4, 1)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_topFarTie (v := 0) ([] : List (List (Option TrioSeq))) (RawUs_nil 0) (by simp [NoTie]) ([] : List (Option TrioSeq)) (RawU_nil 0) (by simp [NoTie]) (WordsG_consT (v := 0) (TF_tieG (u := 0) (TF_nil 0) (GF_of_GPF (GPF_of_PVF (PVF_snoc (A := []) (o := 1) (by decide) (PVF_farW_Fr (o := 1) (by decide) le_rfl (fun k hk => (OkWsk_nil k 0)) (fun k hk => (okWkF_nil k 0))) (RLF_child (A := []) (o := 1) (by decide) (by decide) (by decide) (b := 0) (τ := 2) [1] (by decide) (by decide) (RLF_nil (A := []) (o := 1) (by decide) (by decide) (by decide) 0) (GPF_of_PVF (PVF_snoc (A := [1]) (o := 2) (by decide) (PVF_farWA_F (A0 := [1]) (o := 2) (by decide) (by decide) (by decide) le_rfl (fun k hk => (OkWsA_nil [1] k 0)) (fun k hk => (okRA_nil [1] k 0))) (RLF_child (A := [1]) (o := 2) (by decide) (by decide) (by decide) (b := 0) (τ := 3) [2, 1] (by decide) (by decide) (RLF_nil (A := [1]) (o := 2) (by decide) (by decide) (by decide) 0) (GPF_of_PVF (PVF_snoc (A := [2, 1]) (o := 3) (by decide) (PVF_farWA_F (A0 := [2, 1]) (o := 3) (by decide) (by decide) (by decide) le_rfl (fun k hk => (OkWsA_nil [2, 1] k 0)) (fun k hk => (okRA_nil [2, 1] k 0))) (RLF_nil (A := [2, 1]) (o := 3) (by decide) (by decide) (by decide) 0))))))))))) (WordsG_nil 0))))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop, farW, fwW, mlift_zero, Nat.sub_self] using h

end HaH
end TRIO
