/-
HbY.lean: tools/gen_gyk.py が生成。錨の列つきの子の述語で証明するシート行。
-/
import GzJ
import GzS
import HaJ
import HaL
import HaP
import HaT
import HaV
import HaZ
import HbB
import HbK
import HbV
import HbX

namespace TRIO
namespace HbY

open Wset Small GwS Gw GwU GwZ GxD GxG GxJ GxK GxL GxN GxP GxR GxT GxV GxW GxY
open GyA GyB GyC GyD GyE GyF GyG GyH GyI GyJ GyK GzD GzF GzH GzI GzJ GzM GzN GzP GzS GzU GzV GzW GzY HaA HaC HaD HaE HaF HaG HaJ HaL HaN HaP HaR HaS HaT HaV HaZ HbB HbJ HbK

/-- ★ シート行 1583。 -/
theorem R1583_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 1, 0), (3, 1, 0)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (HbX.starOK_CLF (v := 0) ([] : List (List TrioSeq × List (Option TrioSeq))) (HbV.PsL_nil 0) ([] : List TrioSeq) (HbV.DsOK_nil 0) (unitsC 0 ([] : List (Option TrioSeq))) (HbV.LoadSeq_of (by simp [NoTie]) (RawU_nil 0)) (WordsG_nil 0)))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop, farW, fwW, mlift_zero, Nat.sub_self, HaL.PfF, HaI.towF, HaI.Pf, HaN.QFn, HaN.QF, HaN.towQ, HaN.Lw, List.replicate, HaZ.QP, HaZ.QNil, HbB.wT, HbK.wN, HbD.farWn, HbD.fwWn, HbD.FT, HbV.wL, HbP.FTL0] using h

/-- ★ シート行 1584。 -/
theorem R1584_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 1, 0), (3, 1, 0), (1, 1, 0), (2, 2, 1), (3, 2, 1), (3, 2, 0), (4, 1, 0)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_hang (HbX.starOK_CLF (v := 0) ([] : List (List TrioSeq × List (Option TrioSeq))) (HbV.PsL_nil 0) ([] : List TrioSeq) (HbV.DsOK_nil 0) (unitsC 0 ([] : List (Option TrioSeq))) (HbV.LoadSeq_of (by simp [NoTie]) (RawU_nil 0)) (WordsG_nil 0)) (Wg_of_starOK (HbV.starOK_CL (v := 1) ([(([unitsC 1 ([some ([(0, 1, 0)] : TrioSeq)] : List (Option TrioSeq))] : List TrioSeq), ([] : List (Option TrioSeq)))] : List (List TrioSeq × List (Option TrioSeq))) (HbV.PsL_cons (HbV.DsOK_cons (HbV.LoadSeq_of (by simp [NoTie]) (RawU_cons_some (show ([(0, 1, 0)] : TrioSeq) ∈ Wg (2 * 1) by have h := Wg_up (w := 2 * 1) (Wg_of_starOK (starOK_wordsG (v := 1) (WordsG_nil 1))) (by omega); simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop, farW, fwW, mlift_zero, Nat.sub_self, HaL.PfF, HaI.towF, HaI.Pf, HaN.QFn, HaN.QF, HaN.towQ, HaN.Lw, List.replicate, HaZ.QP, HaZ.QNil, HbB.wT, HbK.wN, HbD.farWn, HbD.fwWn, HbD.FT, HbV.wL, HbP.FTL0] using h) rfl (RawU_nil 1))) (HbV.DsOK_nil 1)) (by simp [NoTie]) (RawU_nil 1) (HbV.PsL_nil 1)) (WordsG_nil 1))) rfl))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop, farW, fwW, mlift_zero, Nat.sub_self, HaL.PfF, HaI.towF, HaI.Pf, HaN.QFn, HaN.QF, HaN.towQ, HaN.Lw, List.replicate, HaZ.QP, HaZ.QNil, HbB.wT, HbK.wN, HbD.farWn, HbD.fwWn, HbD.FT, HbV.wL, HbP.FTL0] using h

/-- ★ シート行 1585。 -/
theorem R1585_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 1, 0), (3, 1, 0), (1, 1, 0), (2, 2, 1), (3, 2, 1), (3, 2, 0), (4, 1, 0), (2, 2, 1), (3, 2, 1)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_hang (HbX.starOK_CLF (v := 0) ([] : List (List TrioSeq × List (Option TrioSeq))) (HbV.PsL_nil 0) ([] : List TrioSeq) (HbV.DsOK_nil 0) (unitsC 0 ([] : List (Option TrioSeq))) (HbV.LoadSeq_of (by simp [NoTie]) (RawU_nil 0)) (WordsG_nil 0)) (Wg_of_starOK (HbV.starOK_CL (v := 1) ([(([unitsC 1 ([some ([(0, 1, 0)] : TrioSeq)] : List (Option TrioSeq))] : List TrioSeq), ([] : List (Option TrioSeq))), (([] : List TrioSeq), ([] : List (Option TrioSeq)))] : List (List TrioSeq × List (Option TrioSeq))) (HbV.PsL_cons (HbV.DsOK_cons (HbV.LoadSeq_of (by simp [NoTie]) (RawU_cons_some (show ([(0, 1, 0)] : TrioSeq) ∈ Wg (2 * 1) by have h := Wg_up (w := 2 * 1) (Wg_of_starOK (starOK_wordsG (v := 1) (WordsG_nil 1))) (by omega); simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop, farW, fwW, mlift_zero, Nat.sub_self, HaL.PfF, HaI.towF, HaI.Pf, HaN.QFn, HaN.QF, HaN.towQ, HaN.Lw, List.replicate, HaZ.QP, HaZ.QNil, HbB.wT, HbK.wN, HbD.farWn, HbD.fwWn, HbD.FT, HbV.wL, HbP.FTL0] using h) rfl (RawU_nil 1))) (HbV.DsOK_nil 1)) (by simp [NoTie]) (RawU_nil 1) (HbV.PsL_cons (HbV.DsOK_nil 1) (by simp [NoTie]) (RawU_nil 1) (HbV.PsL_nil 1))) (WordsG_nil 1))) rfl))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop, farW, fwW, mlift_zero, Nat.sub_self, HaL.PfF, HaI.towF, HaI.Pf, HaN.QFn, HaN.QF, HaN.towQ, HaN.Lw, List.replicate, HaZ.QP, HaZ.QNil, HbB.wT, HbK.wN, HbD.farWn, HbD.fwWn, HbD.FT, HbV.wL, HbP.FTL0] using h

/-- ★ シート行 1586。 -/
theorem R1586_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 1, 0), (3, 1, 0), (1, 1, 0), (2, 2, 1), (3, 2, 1), (3, 2, 0), (4, 1, 0), (2, 2, 1), (3, 2, 1), (3, 2, 0), (4, 1, 0)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_hang (HbX.starOK_CLF (v := 0) ([] : List (List TrioSeq × List (Option TrioSeq))) (HbV.PsL_nil 0) ([] : List TrioSeq) (HbV.DsOK_nil 0) (unitsC 0 ([] : List (Option TrioSeq))) (HbV.LoadSeq_of (by simp [NoTie]) (RawU_nil 0)) (WordsG_nil 0)) (Wg_of_starOK (HbV.starOK_CL (v := 1) ([(([unitsC 1 ([some ([(0, 1, 0)] : TrioSeq)] : List (Option TrioSeq))] : List TrioSeq), ([] : List (Option TrioSeq))), (([unitsC 1 ([some ([(0, 1, 0)] : TrioSeq)] : List (Option TrioSeq))] : List TrioSeq), ([] : List (Option TrioSeq)))] : List (List TrioSeq × List (Option TrioSeq))) (HbV.PsL_cons (HbV.DsOK_cons (HbV.LoadSeq_of (by simp [NoTie]) (RawU_cons_some (show ([(0, 1, 0)] : TrioSeq) ∈ Wg (2 * 1) by have h := Wg_up (w := 2 * 1) (Wg_of_starOK (starOK_wordsG (v := 1) (WordsG_nil 1))) (by omega); simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop, farW, fwW, mlift_zero, Nat.sub_self, HaL.PfF, HaI.towF, HaI.Pf, HaN.QFn, HaN.QF, HaN.towQ, HaN.Lw, List.replicate, HaZ.QP, HaZ.QNil, HbB.wT, HbK.wN, HbD.farWn, HbD.fwWn, HbD.FT, HbV.wL, HbP.FTL0] using h) rfl (RawU_nil 1))) (HbV.DsOK_nil 1)) (by simp [NoTie]) (RawU_nil 1) (HbV.PsL_cons (HbV.DsOK_cons (HbV.LoadSeq_of (by simp [NoTie]) (RawU_cons_some (show ([(0, 1, 0)] : TrioSeq) ∈ Wg (2 * 1) by have h := Wg_up (w := 2 * 1) (Wg_of_starOK (starOK_wordsG (v := 1) (WordsG_nil 1))) (by omega); simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop, farW, fwW, mlift_zero, Nat.sub_self, HaL.PfF, HaI.towF, HaI.Pf, HaN.QFn, HaN.QF, HaN.towQ, HaN.Lw, List.replicate, HaZ.QP, HaZ.QNil, HbB.wT, HbK.wN, HbD.farWn, HbD.fwWn, HbD.FT, HbV.wL, HbP.FTL0] using h) rfl (RawU_nil 1))) (HbV.DsOK_nil 1)) (by simp [NoTie]) (RawU_nil 1) (HbV.PsL_nil 1))) (WordsG_nil 1))) rfl))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop, farW, fwW, mlift_zero, Nat.sub_self, HaL.PfF, HaI.towF, HaI.Pf, HaN.QFn, HaN.QF, HaN.towQ, HaN.Lw, List.replicate, HaZ.QP, HaZ.QNil, HbB.wT, HbK.wN, HbD.farWn, HbD.fwWn, HbD.FT, HbV.wL, HbP.FTL0] using h

/-- ★ シート行 1587。 -/
theorem R1587_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 1, 0), (3, 1, 0), (1, 1, 0), (2, 2, 1), (3, 2, 1), (3, 2, 0), (4, 1, 0), (3, 1, 0)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_hang (HbX.starOK_CLF (v := 0) ([] : List (List TrioSeq × List (Option TrioSeq))) (HbV.PsL_nil 0) ([] : List TrioSeq) (HbV.DsOK_nil 0) (unitsC 0 ([] : List (Option TrioSeq))) (HbV.LoadSeq_of (by simp [NoTie]) (RawU_nil 0)) (WordsG_nil 0)) (Wg_of_starOK (HbV.starOK_CL (v := 1) ([(([unitsC 1 ([some ([(0, 1, 0)] : TrioSeq)] : List (Option TrioSeq))] : List TrioSeq), ([some ([(0, 1, 0)] : TrioSeq)] : List (Option TrioSeq)))] : List (List TrioSeq × List (Option TrioSeq))) (HbV.PsL_cons (HbV.DsOK_cons (HbV.LoadSeq_of (by simp [NoTie]) (RawU_cons_some (show ([(0, 1, 0)] : TrioSeq) ∈ Wg (2 * 1) by have h := Wg_up (w := 2 * 1) (Wg_of_starOK (starOK_wordsG (v := 1) (WordsG_nil 1))) (by omega); simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop, farW, fwW, mlift_zero, Nat.sub_self, HaL.PfF, HaI.towF, HaI.Pf, HaN.QFn, HaN.QF, HaN.towQ, HaN.Lw, List.replicate, HaZ.QP, HaZ.QNil, HbB.wT, HbK.wN, HbD.farWn, HbD.fwWn, HbD.FT, HbV.wL, HbP.FTL0] using h) rfl (RawU_nil 1))) (HbV.DsOK_nil 1)) (by simp [NoTie]) (RawU_cons_some (show ([(0, 1, 0)] : TrioSeq) ∈ Wg (2 * 1) by have h := Wg_up (w := 2 * 1) (Wg_of_starOK (starOK_wordsG (v := 1) (WordsG_nil 1))) (by omega); simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop, farW, fwW, mlift_zero, Nat.sub_self, HaL.PfF, HaI.towF, HaI.Pf, HaN.QFn, HaN.QF, HaN.towQ, HaN.Lw, List.replicate, HaZ.QP, HaZ.QNil, HbB.wT, HbK.wN, HbD.farWn, HbD.fwWn, HbD.FT, HbV.wL, HbP.FTL0] using h) rfl (RawU_nil 1)) (HbV.PsL_nil 1)) (WordsG_nil 1))) rfl))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop, farW, fwW, mlift_zero, Nat.sub_self, HaL.PfF, HaI.towF, HaI.Pf, HaN.QFn, HaN.QF, HaN.towQ, HaN.Lw, List.replicate, HaZ.QP, HaZ.QNil, HbB.wT, HbK.wN, HbD.farWn, HbD.fwWn, HbD.FT, HbV.wL, HbP.FTL0] using h

/-- ★ シート行 1588。 -/
theorem R1588_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 1, 0), (3, 1, 0), (1, 1, 0), (2, 2, 1), (3, 2, 1), (3, 2, 0), (4, 1, 0), (3, 2, 0), (2, 2, 1), (3, 2, 1)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_hang (HbX.starOK_CLF (v := 0) ([] : List (List TrioSeq × List (Option TrioSeq))) (HbV.PsL_nil 0) ([] : List TrioSeq) (HbV.DsOK_nil 0) (unitsC 0 ([] : List (Option TrioSeq))) (HbV.LoadSeq_of (by simp [NoTie]) (RawU_nil 0)) (WordsG_nil 0)) (Wg_of_starOK (HbV.starOK_CL (v := 1) ([(([unitsC 1 ([some ([(0, 1, 0)] : TrioSeq)] : List (Option TrioSeq)), unitsC 1 ([] : List (Option TrioSeq))] : List TrioSeq), ([] : List (Option TrioSeq))), (([] : List TrioSeq), ([] : List (Option TrioSeq)))] : List (List TrioSeq × List (Option TrioSeq))) (HbV.PsL_cons (HbV.DsOK_cons (HbV.LoadSeq_of (by simp [NoTie]) (RawU_cons_some (show ([(0, 1, 0)] : TrioSeq) ∈ Wg (2 * 1) by have h := Wg_up (w := 2 * 1) (Wg_of_starOK (starOK_wordsG (v := 1) (WordsG_nil 1))) (by omega); simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop, farW, fwW, mlift_zero, Nat.sub_self, HaL.PfF, HaI.towF, HaI.Pf, HaN.QFn, HaN.QF, HaN.towQ, HaN.Lw, List.replicate, HaZ.QP, HaZ.QNil, HbB.wT, HbK.wN, HbD.farWn, HbD.fwWn, HbD.FT, HbV.wL, HbP.FTL0] using h) rfl (RawU_nil 1))) (HbV.DsOK_cons (HbV.LoadSeq_of (by simp [NoTie]) (RawU_nil 1)) (HbV.DsOK_nil 1))) (by simp [NoTie]) (RawU_nil 1) (HbV.PsL_cons (HbV.DsOK_nil 1) (by simp [NoTie]) (RawU_nil 1) (HbV.PsL_nil 1))) (WordsG_nil 1))) rfl))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop, farW, fwW, mlift_zero, Nat.sub_self, HaL.PfF, HaI.towF, HaI.Pf, HaN.QFn, HaN.QF, HaN.towQ, HaN.Lw, List.replicate, HaZ.QP, HaZ.QNil, HbB.wT, HbK.wN, HbD.farWn, HbD.fwWn, HbD.FT, HbV.wL, HbP.FTL0] using h

/-- ★ シート行 1589。 -/
theorem R1589_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 1, 0), (3, 1, 0), (1, 1, 0), (2, 2, 1), (3, 2, 1), (3, 2, 0), (4, 1, 0), (3, 2, 0), (4, 1, 0)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_hang (HbX.starOK_CLF (v := 0) ([] : List (List TrioSeq × List (Option TrioSeq))) (HbV.PsL_nil 0) ([] : List TrioSeq) (HbV.DsOK_nil 0) (unitsC 0 ([] : List (Option TrioSeq))) (HbV.LoadSeq_of (by simp [NoTie]) (RawU_nil 0)) (WordsG_nil 0)) (Wg_of_starOK (HbV.starOK_CL (v := 1) ([(([unitsC 1 ([some ([(0, 1, 0)] : TrioSeq)] : List (Option TrioSeq)), unitsC 1 ([some ([(0, 1, 0)] : TrioSeq)] : List (Option TrioSeq))] : List TrioSeq), ([] : List (Option TrioSeq)))] : List (List TrioSeq × List (Option TrioSeq))) (HbV.PsL_cons (HbV.DsOK_cons (HbV.LoadSeq_of (by simp [NoTie]) (RawU_cons_some (show ([(0, 1, 0)] : TrioSeq) ∈ Wg (2 * 1) by have h := Wg_up (w := 2 * 1) (Wg_of_starOK (starOK_wordsG (v := 1) (WordsG_nil 1))) (by omega); simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop, farW, fwW, mlift_zero, Nat.sub_self, HaL.PfF, HaI.towF, HaI.Pf, HaN.QFn, HaN.QF, HaN.towQ, HaN.Lw, List.replicate, HaZ.QP, HaZ.QNil, HbB.wT, HbK.wN, HbD.farWn, HbD.fwWn, HbD.FT, HbV.wL, HbP.FTL0] using h) rfl (RawU_nil 1))) (HbV.DsOK_cons (HbV.LoadSeq_of (by simp [NoTie]) (RawU_cons_some (show ([(0, 1, 0)] : TrioSeq) ∈ Wg (2 * 1) by have h := Wg_up (w := 2 * 1) (Wg_of_starOK (starOK_wordsG (v := 1) (WordsG_nil 1))) (by omega); simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop, farW, fwW, mlift_zero, Nat.sub_self, HaL.PfF, HaI.towF, HaI.Pf, HaN.QFn, HaN.QF, HaN.towQ, HaN.Lw, List.replicate, HaZ.QP, HaZ.QNil, HbB.wT, HbK.wN, HbD.farWn, HbD.fwWn, HbD.FT, HbV.wL, HbP.FTL0] using h) rfl (RawU_nil 1))) (HbV.DsOK_nil 1))) (by simp [NoTie]) (RawU_nil 1) (HbV.PsL_nil 1)) (WordsG_nil 1))) rfl))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop, farW, fwW, mlift_zero, Nat.sub_self, HaL.PfF, HaI.towF, HaI.Pf, HaN.QFn, HaN.QF, HaN.towQ, HaN.Lw, List.replicate, HaZ.QP, HaZ.QNil, HbB.wT, HbK.wN, HbD.farWn, HbD.fwWn, HbD.FT, HbV.wL, HbP.FTL0] using h

/-- ★ シート行 1590。 -/
theorem R1590_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 1, 0), (3, 1, 0), (1, 1, 0), (2, 2, 1), (3, 2, 1), (3, 2, 0), (4, 1, 0), (4, 1, 0)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_hang (HbX.starOK_CLF (v := 0) ([] : List (List TrioSeq × List (Option TrioSeq))) (HbV.PsL_nil 0) ([] : List TrioSeq) (HbV.DsOK_nil 0) (unitsC 0 ([] : List (Option TrioSeq))) (HbV.LoadSeq_of (by simp [NoTie]) (RawU_nil 0)) (WordsG_nil 0)) (Wg_of_starOK (HbV.starOK_CL (v := 1) ([(([unitsC 1 ([some ([(0, 1, 0)] : TrioSeq), some ([(0, 1, 0)] : TrioSeq)] : List (Option TrioSeq))] : List TrioSeq), ([] : List (Option TrioSeq)))] : List (List TrioSeq × List (Option TrioSeq))) (HbV.PsL_cons (HbV.DsOK_cons (HbV.LoadSeq_of (by simp [NoTie]) (RawU_cons_some (show ([(0, 1, 0)] : TrioSeq) ∈ Wg (2 * 1) by have h := Wg_up (w := 2 * 1) (Wg_of_starOK (starOK_wordsG (v := 1) (WordsG_nil 1))) (by omega); simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop, farW, fwW, mlift_zero, Nat.sub_self, HaL.PfF, HaI.towF, HaI.Pf, HaN.QFn, HaN.QF, HaN.towQ, HaN.Lw, List.replicate, HaZ.QP, HaZ.QNil, HbB.wT, HbK.wN, HbD.farWn, HbD.fwWn, HbD.FT, HbV.wL, HbP.FTL0] using h) rfl (RawU_cons_some (show ([(0, 1, 0)] : TrioSeq) ∈ Wg (2 * 1) by have h := Wg_up (w := 2 * 1) (Wg_of_starOK (starOK_wordsG (v := 1) (WordsG_nil 1))) (by omega); simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop, farW, fwW, mlift_zero, Nat.sub_self, HaL.PfF, HaI.towF, HaI.Pf, HaN.QFn, HaN.QF, HaN.towQ, HaN.Lw, List.replicate, HaZ.QP, HaZ.QNil, HbB.wT, HbK.wN, HbD.farWn, HbD.fwWn, HbD.FT, HbV.wL, HbP.FTL0] using h) rfl (RawU_nil 1)))) (HbV.DsOK_nil 1)) (by simp [NoTie]) (RawU_nil 1) (HbV.PsL_nil 1)) (WordsG_nil 1))) rfl))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop, farW, fwW, mlift_zero, Nat.sub_self, HaL.PfF, HaI.towF, HaI.Pf, HaN.QFn, HaN.QF, HaN.towQ, HaN.Lw, List.replicate, HaZ.QP, HaZ.QNil, HbB.wT, HbK.wN, HbD.farWn, HbD.fwWn, HbD.FT, HbV.wL, HbP.FTL0] using h

/-- ★ シート行 1591。 -/
theorem R1591_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 1, 0), (3, 1, 0), (1, 1, 0), (2, 2, 1), (3, 2, 1), (3, 2, 0), (4, 2, 0)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_hang (HbX.starOK_CLF (v := 0) ([] : List (List TrioSeq × List (Option TrioSeq))) (HbV.PsL_nil 0) ([] : List TrioSeq) (HbV.DsOK_nil 0) (unitsC 0 ([] : List (Option TrioSeq))) (HbV.LoadSeq_of (by simp [NoTie]) (RawU_nil 0)) (WordsG_nil 0)) (Wg_of_starOK (HbX.starOK_CLF (v := 1) ([] : List (List TrioSeq × List (Option TrioSeq))) (HbV.PsL_nil 1) ([] : List TrioSeq) (HbV.DsOK_nil 1) (unitsC 1 ([] : List (Option TrioSeq))) (HbV.LoadSeq_of (by simp [NoTie]) (RawU_nil 1)) (WordsG_nil 1))) rfl))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop, farW, fwW, mlift_zero, Nat.sub_self, HaL.PfF, HaI.towF, HaI.Pf, HaN.QFn, HaN.QF, HaN.towQ, HaN.Lw, List.replicate, HaZ.QP, HaZ.QNil, HbB.wT, HbK.wN, HbD.farWn, HbD.fwWn, HbD.FT, HbV.wL, HbP.FTL0] using h

/-- ★ シート行 1592。 -/
theorem R1592_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 1, 0), (3, 1, 0), (1, 1, 0), (2, 2, 1), (3, 2, 1), (3, 2, 0), (4, 2, 0), (2, 2, 0), (3, 3, 1), (4, 3, 1), (4, 3, 0), (5, 3, 0)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (starOK_hang (HbX.starOK_CLF (v := 0) ([] : List (List TrioSeq × List (Option TrioSeq))) (HbV.PsL_nil 0) ([] : List TrioSeq) (HbV.DsOK_nil 0) (unitsC 0 ([] : List (Option TrioSeq))) (HbV.LoadSeq_of (by simp [NoTie]) (RawU_nil 0)) (WordsG_nil 0)) (Wg_of_starOK (starOK_hang (HbX.starOK_CLF (v := 1) ([] : List (List TrioSeq × List (Option TrioSeq))) (HbV.PsL_nil 1) ([] : List TrioSeq) (HbV.DsOK_nil 1) (unitsC 1 ([] : List (Option TrioSeq))) (HbV.LoadSeq_of (by simp [NoTie]) (RawU_nil 1)) (WordsG_nil 1)) (Wg_of_starOK (HbX.starOK_CLF (v := 2) ([] : List (List TrioSeq × List (Option TrioSeq))) (HbV.PsL_nil 2) ([] : List TrioSeq) (HbV.DsOK_nil 2) (unitsC 2 ([] : List (Option TrioSeq))) (HbV.LoadSeq_of (by simp [NoTie]) (RawU_nil 2)) (WordsG_nil 2))) rfl)) rfl))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop, farW, fwW, mlift_zero, Nat.sub_self, HaL.PfF, HaI.towF, HaI.Pf, HaN.QFn, HaN.QF, HaN.towQ, HaN.Lw, List.replicate, HaZ.QP, HaZ.QNil, HbB.wT, HbK.wN, HbD.farWn, HbD.fwWn, HbD.FT, HbV.wL, HbP.FTL0] using h

/-- ★ シート行 1593。 -/
theorem R1593_mem : ([(0, 0, 0), (1, 1, 1), (2, 1, 1), (2, 1, 0), (3, 1, 0), (1, 1, 1)] : TrioSeq) ∈ W 0 := by
  have h := GxB.Wg0_sub_W0 (Wg_of_starOK (HbX.starOK_CLF (v := 0) ([] : List (List TrioSeq × List (Option TrioSeq))) (HbV.PsL_nil 0) ([] : List TrioSeq) (HbV.DsOK_nil 0) (unitsC 0 ([] : List (Option TrioSeq))) (HbV.LoadSeq_of (by simp [NoTie]) (RawU_nil 0)) (WordsG_consT (v := 0) (TF_nil 0) (WordsG_nil 0))))
  simpa [shiftr01, rword, rcol, farR, farU, fwU, unitsC, unitC, fwTop, farW, fwW, mlift_zero, Nat.sub_self, HaL.PfF, HaI.towF, HaI.Pf, HaN.QFn, HaN.QF, HaN.towQ, HaN.Lw, List.replicate, HaZ.QP, HaZ.QNil, HbB.wT, HbK.wN, HbD.farWn, HbD.fwWn, HbD.FT, HbV.wL, HbP.FTL0] using h

end HbY
end TRIO
