name = "trio"
defaultTargets = ["TRIO"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.30.0"

[[lean_lib]]
name = "TRIO"
roots = ["Trio", "Term", "Decrease", "Reduction", "Seqlex", "Cnf", "Lift", "Gcopy", "Goper", "Cofinality", "ArgDom", "Column", "Invariant", "Zjump", "Gtrans", "Peel2", "Core", "Wset", "Wchar", "Lcone", "Cgraft", "Aexp", "Wslift", "Wtower2", "Croot", "Xbar", "Gamma", "Lind", "Infcex", "L47W", "L51Tower", "L53Subst", "L105Cap", "H12Export", "R2LT", "Final", "Cofidx", "SmallA", "Small", "Gw", "GwS", "GwT", "GwU", "GwV", "GwW", "GwX", "GwY", "GwZ", "GxA", "GxB", "GxC", "GxD", "GxE", "GxF", "GxG", "GxH", "GxI", "GxJ", "GxK", "GxL", "GxM", "GxN", "GxO", "GxP", "GxQ", "GxR", "GxS", "GxT", "GxU", "GxV", "GxW", "GxX", "GxY", "GxZ", "GyA", "GyB", "Pair.Pss", "Pair.Term", "Pair.Decrease", "Pair.Reduction", "Pair.Cnf", "Pair.Seqlex", "Pair.Column", "Pair.Cofinality", "Pair.ArgDom", "Pair.Wset", "Pair.Final", "Pair.Bridge"]
